export interface Theme {
  id: string;
  name: string;
  nameZh: string;
  emoji: string;
  description: string;
  isDark: boolean;
  colors: {
    primary: string;
    primaryLight: string;
    secondary: string;
    accent: string;
    warning: string;
    success: string;
    bg: string;
    cardBg: string;
    textPrimary: string;
    textSecondary: string;
    textMuted: string;
    border: string;
    sidebarBg: string;
    sidebarBorder: string;
    inputBg: string;
    inputBorder: string;
  };
  font?: string;
}

export const themes: Theme[] = [
  {
    id: "default",
    name: "Default",
    nameZh: "默认",
    emoji: "🎨",
    description: "The original AI Buddy look",
    isDark: false,
    colors: {
      primary: "#6C5CE7",
      primaryLight: "#A29BFE",
      secondary: "#00CEC9",
      accent: "#FD79A8",
      warning: "#FDCB6E",
      success: "#00B894",
      bg: "#FAFAFA",
      cardBg: "#FFFFFF",
      textPrimary: "#111827",
      textSecondary: "#6B7280",
      textMuted: "#9CA3AF",
      border: "#F3F4F6",
      sidebarBg: "#FFFFFF",
      sidebarBorder: "#F3F4F6",
      inputBg: "#F3F4F6",
      inputBorder: "#E5E7EB",
    },
  },
  {
    id: "sakura",
    name: "Sakura",
    nameZh: "樱花",
    emoji: "🌸",
    description: "Soft and cute pink vibes",
    isDark: false,
    colors: {
      primary: "#DB2777",
      primaryLight: "#F472B6",
      secondary: "#FDA4AF",
      accent: "#FBCFE8",
      warning: "#FDCB6E",
      success: "#34D399",
      bg: "#FFF1F2",
      cardBg: "#FFFFFF",
      textPrimary: "#1F2937",
      textSecondary: "#6B7280",
      textMuted: "#9CA3AF",
      border: "#FCE7F3",
      sidebarBg: "#FFF1F2",
      sidebarBorder: "#FCE7F3",
      inputBg: "#FFF1F2",
      inputBorder: "#FBCFE8",
    },
  },
  {
    id: "magic",
    name: "Magic",
    nameZh: "魔法",
    emoji: "✨",
    description: "Stars and sparkles everywhere",
    isDark: false,
    colors: {
      primary: "#9333EA",
      primaryLight: "#A78BFA",
      secondary: "#FBBF24",
      accent: "#A78BFA",
      warning: "#FBBF24",
      success: "#34D399",
      bg: "#FAF5FF",
      cardBg: "#FFFFFF",
      textPrimary: "#1F2937",
      textSecondary: "#6B7280",
      textMuted: "#9CA3AF",
      border: "#F3E8FF",
      sidebarBg: "#FAF5FF",
      sidebarBorder: "#F3E8FF",
      inputBg: "#FAF5FF",
      inputBorder: "#E9D5FF",
    },
  },
  {
    id: "space",
    name: "Space",
    nameZh: "太空",
    emoji: "🚀",
    description: "Sci-fi neon in the cosmos",
    isDark: true,
    colors: {
      primary: "#818CF8",
      primaryLight: "#A5B4FC",
      secondary: "#22D3EE",
      accent: "#60A5FA",
      warning: "#FBBF24",
      success: "#34D399",
      bg: "#0F172A",
      cardBg: "#1E293B",
      textPrimary: "#F1F5F9",
      textSecondary: "#CBD5E1",
      textMuted: "#94A3B8",
      border: "#334155",
      sidebarBg: "#1E293B",
      sidebarBorder: "#334155",
      inputBg: "#1E293B",
      inputBorder: "#475569",
    },
  },
  {
    id: "cyber",
    name: "Cyber",
    nameZh: "科技",
    emoji: "💻",
    description: "Hacker matrix style",
    isDark: true,
    colors: {
      primary: "#22C55E",
      primaryLight: "#4ADE80",
      secondary: "#34D399",
      accent: "#A3E635",
      warning: "#FBBF24",
      success: "#34D399",
      bg: "#030712",
      cardBg: "#111827",
      textPrimary: "#F0FDF4",
      textSecondary: "#86EFAC",
      textMuted: "#4ADE80",
      border: "#1F2937",
      sidebarBg: "#111827",
      sidebarBorder: "#1F2937",
      inputBg: "#111827",
      inputBorder: "#374151",
    },
  },
  {
    id: "ocean",
    name: "Ocean",
    nameZh: "海洋",
    emoji: "🌊",
    description: "Fresh and breezy waves",
    isDark: false,
    colors: {
      primary: "#0D9488",
      primaryLight: "#14B8A6",
      secondary: "#38BDF8",
      accent: "#67E8F9",
      warning: "#FBBF24",
      success: "#34D399",
      bg: "#F0F9FF",
      cardBg: "#FFFFFF",
      textPrimary: "#0F172A",
      textSecondary: "#64748B",
      textMuted: "#94A3B8",
      border: "#E0F2FE",
      sidebarBg: "#F0F9FF",
      sidebarBorder: "#E0F2FE",
      inputBg: "#F0F9FF",
      inputBorder: "#BAE6FD",
    },
  },
  {
    id: "arcade",
    name: "Arcade",
    nameZh: "游戏",
    emoji: "🕹️",
    description: "Retro pixel vibes",
    isDark: false,
    font: "'Press Start 2P', monospace",
    colors: {
      primary: "#B45309",
      primaryLight: "#D97706",
      secondary: "#EF4444",
      accent: "#3B82F6",
      warning: "#FBBF24",
      success: "#22C55E",
      bg: "#FEFCE8",
      cardBg: "#FFFFFF",
      textPrimary: "#1C1917",
      textSecondary: "#78716C",
      textMuted: "#A8A29E",
      border: "#FEF9C3",
      sidebarBg: "#FEFCE8",
      sidebarBorder: "#FEF9C3",
      inputBg: "#FEFCE8",
      inputBorder: "#FDE68A",
    },
  },
  {
    id: "nature",
    name: "Nature",
    nameZh: "自然",
    emoji: "🌿",
    description: "Fresh and natural greens",
    isDark: false,
    colors: {
      primary: "#16A34A",
      primaryLight: "#4ADE80",
      secondary: "#A3E635",
      accent: "#6EE7B7",
      warning: "#FBBF24",
      success: "#22C55E",
      bg: "#F0FDF4",
      cardBg: "#FFFFFF",
      textPrimary: "#14532D",
      textSecondary: "#6B7280",
      textMuted: "#9CA3AF",
      border: "#DCFCE7",
      sidebarBg: "#F0FDF4",
      sidebarBorder: "#DCFCE7",
      inputBg: "#F0FDF4",
      inputBorder: "#BBF7D0",
    },
  },
  {
    id: "flame",
    name: "Flame",
    nameZh: "烈焰",
    emoji: "🔥",
    description: "Cool blazing fire style",
    isDark: false,
    colors: {
      primary: "#EA580C",
      primaryLight: "#FB923C",
      secondary: "#EF4444",
      accent: "#F59E0B",
      warning: "#FBBF24",
      success: "#34D399",
      bg: "#FFF7ED",
      cardBg: "#FFFFFF",
      textPrimary: "#1C1917",
      textSecondary: "#78716C",
      textMuted: "#A8A29E",
      border: "#FFEDD5",
      sidebarBg: "#FFF7ED",
      sidebarBorder: "#FFEDD5",
      inputBg: "#FFF7ED",
      inputBorder: "#FED7AA",
    },
  },
];

export function getThemeById(id: string): Theme {
  return themes.find((t) => t.id === id) || themes[0];
}
