// Auto-generated by gen-cpp-part6.js
import type { CppExercise } from './cpp-exercises';

export const CPP_EXERCISES_PART6: CppExercise[] = [
  {
    "id": "cpp-ex-5-11",
    "title": "Vector Push & Print",
    "titleZh": "向量添加与打印",
    "difficulty": "hard",
    "level": 5,
    "category": "STL Containers",
    "categoryZh": "STL容器",
    "tags": [
      "vector",
      "push_back",
      "iteration"
    ],
    "description": "Read n integers, push them into a vector, then print all elements space-separated.\n\nInput: n followed by n integers\nOutput: elements space-separated",
    "descriptionZh": "读取n个整数存入vector，空格分隔输出。",
    "examples": [
      {
        "input": "4\n10 20 30 40",
        "output": "10 20 30 40"
      }
    ],
    "starterCode": "#include <iostream>\n#include <vector>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    vector<int> v;\n    // TODO: read, push_back, print\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <vector>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    vector<int> v;\n    for (int i = 0; i < n; i++) {\n        int x; cin >> x;\n        v.push_back(x);\n    }\n    for (int i = 0; i < (int)v.size(); i++) {\n        if (i) cout << \" \";\n        cout << v[i];\n    }\n    cout << endl;\n    return 0;\n}",
    "hints": [
      "Use push_back to add elements",
      "Use size() to get length"
    ],
    "hintsZh": [
      "用push_back添加元素",
      "用size()获取长度"
    ],
    "testCases": [
      {
        "input": "4\n10 20 30 40",
        "expectedOutput": "10 20 30 40"
      },
      {
        "input": "1\n5",
        "expectedOutput": "5"
      },
      {
        "input": "3\n-1 0 1",
        "expectedOutput": "-1 0 1"
      }
    ]
  },
  {
    "id": "cpp-ex-5-12",
    "title": "Vector Erase & Insert",
    "titleZh": "向量删除与插入",
    "difficulty": "hard",
    "level": 5,
    "category": "STL Containers",
    "categoryZh": "STL容器",
    "tags": [
      "vector",
      "erase",
      "insert"
    ],
    "description": "Read n integers into a vector. Then read position p and value val. Insert val at position p, then erase the last element. Print result.\n\nInput: n, n integers, p val\nOutput: resulting vector space-separated",
    "descriptionZh": "读取n个整数，在位置p插入val，删除最后一个元素，输出结果。",
    "examples": [
      {
        "input": "4\n1 2 3 4\n1 99",
        "output": "1 99 2 3"
      }
    ],
    "starterCode": "#include <iostream>\n#include <vector>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    vector<int> v(n);\n    for (int i = 0; i < n; i++) cin >> v[i];\n    int p, val;\n    cin >> p >> val;\n    // TODO: insert at p, erase last\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <vector>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    vector<int> v(n);\n    for (int i = 0; i < n; i++) cin >> v[i];\n    int p, val;\n    cin >> p >> val;\n    v.insert(v.begin() + p, val);\n    v.erase(v.end() - 1);\n    for (int i = 0; i < (int)v.size(); i++) {\n        if (i) cout << \" \";\n        cout << v[i];\n    }\n    cout << endl;\n    return 0;\n}",
    "hints": [
      "insert takes iterator position",
      "v.begin() + p gives position p"
    ],
    "hintsZh": [
      "insert接受迭代器位置",
      "v.begin() + p 得到位置p"
    ],
    "testCases": [
      {
        "input": "4\n1 2 3 4\n1 99",
        "expectedOutput": "1 99 2 3"
      },
      {
        "input": "3\n5 6 7\n0 10",
        "expectedOutput": "10 5 6"
      },
      {
        "input": "2\n1 2\n2 3",
        "expectedOutput": "1 2"
      }
    ]
  },
  {
    "id": "cpp-ex-5-13",
    "title": "Map Word Frequency",
    "titleZh": "Map词频统计",
    "difficulty": "hard",
    "level": 5,
    "category": "STL Containers",
    "categoryZh": "STL容器",
    "tags": [
      "map",
      "frequency",
      "string"
    ],
    "description": "Read n words. Count frequency of each word using map. Print each word and count in alphabetical order.\n\nInput: n followed by n words\nOutput: each word and count, one per line, alphabetically",
    "descriptionZh": "读取n个单词，用map统计频率，按字母序输出。",
    "examples": [
      {
        "input": "5\napple banana apple cherry banana",
        "output": "apple 2\nbanana 2\ncherry 1"
      }
    ],
    "starterCode": "#include <iostream>\n#include <map>\n#include <string>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    map<string, int> freq;\n    // TODO\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <map>\n#include <string>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    map<string, int> freq;\n    for (int i = 0; i < n; i++) {\n        string w; cin >> w;\n        freq[w]++;\n    }\n    for (auto& p : freq) {\n        cout << p.first << \" \" << p.second << endl;\n    }\n    return 0;\n}",
    "hints": [
      "map keeps keys sorted",
      "freq[word]++ increments count"
    ],
    "hintsZh": [
      "map自动按键排序",
      "freq[word]++递增计数"
    ],
    "testCases": [
      {
        "input": "5\napple banana apple cherry banana",
        "expectedOutput": "apple 2\nbanana 2\ncherry 1"
      },
      {
        "input": "3\na a a",
        "expectedOutput": "a 3"
      },
      {
        "input": "4\nz y x w",
        "expectedOutput": "w 1\nx 1\ny 1\nz 1"
      }
    ]
  },
  {
    "id": "cpp-ex-5-14",
    "title": "Unordered Map Two Sum",
    "titleZh": "哈希表两数之和",
    "difficulty": "hard",
    "level": 5,
    "category": "STL Containers",
    "categoryZh": "STL容器",
    "tags": [
      "unordered_map",
      "two-sum",
      "hash"
    ],
    "description": "Read n integers and a target. Find two indices (0-based) whose values sum to target. Print them in ascending order.\n\nInput: n, n integers, target\nOutput: i j (the two indices, i < j)",
    "descriptionZh": "找到两个数的下标，使其和等于目标值。",
    "examples": [
      {
        "input": "4\n2 7 11 15\n9",
        "output": "0 1"
      }
    ],
    "starterCode": "#include <iostream>\n#include <vector>\n#include <unordered_map>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    vector<int> nums(n);\n    for (int i = 0; i < n; i++) cin >> nums[i];\n    int target; cin >> target;\n    // TODO: find two indices\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <vector>\n#include <unordered_map>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    vector<int> nums(n);\n    for (int i = 0; i < n; i++) cin >> nums[i];\n    int target; cin >> target;\n    unordered_map<int, int> seen;\n    for (int i = 0; i < n; i++) {\n        int comp = target - nums[i];\n        if (seen.count(comp)) {\n            cout << seen[comp] << \" \" << i << endl;\n            return 0;\n        }\n        seen[nums[i]] = i;\n    }\n    return 0;\n}",
    "hints": [
      "Store value->index in hash map",
      "Check if complement exists"
    ],
    "hintsZh": [
      "在哈希表中存值->索引",
      "检查补数是否存在"
    ],
    "testCases": [
      {
        "input": "4\n2 7 11 15\n9",
        "expectedOutput": "0 1"
      },
      {
        "input": "3\n3 2 4\n6",
        "expectedOutput": "1 2"
      },
      {
        "input": "2\n3 3\n6",
        "expectedOutput": "0 1"
      }
    ]
  },
  {
    "id": "cpp-ex-5-15",
    "title": "Set Operations",
    "titleZh": "集合操作",
    "difficulty": "hard",
    "level": 5,
    "category": "STL Containers",
    "categoryZh": "STL容器",
    "tags": [
      "set",
      "insert",
      "unique"
    ],
    "description": "Read n integers, insert into a set. Print the unique elements in sorted order and the count.\n\nInput: n followed by n integers\nOutput: line 1: sorted unique elements, line 2: count",
    "descriptionZh": "读取n个整数插入set，输出去重排序后的元素和个数。",
    "examples": [
      {
        "input": "6\n3 1 4 1 5 3",
        "output": "1 3 4 5\n4"
      }
    ],
    "starterCode": "#include <iostream>\n#include <set>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    set<int> s;\n    // TODO\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <set>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    set<int> s;\n    for (int i = 0; i < n; i++) {\n        int x; cin >> x;\n        s.insert(x);\n    }\n    bool first = true;\n    for (int x : s) {\n        if (!first) cout << \" \";\n        cout << x;\n        first = false;\n    }\n    cout << \"\\n\" << s.size() << endl;\n    return 0;\n}",
    "hints": [
      "set automatically sorts and deduplicates",
      "Use range-for to iterate"
    ],
    "hintsZh": [
      "set自动排序去重",
      "用范围for遍历"
    ],
    "testCases": [
      {
        "input": "6\n3 1 4 1 5 3",
        "expectedOutput": "1 3 4 5\n4"
      },
      {
        "input": "3\n1 1 1",
        "expectedOutput": "1\n1"
      },
      {
        "input": "4\n4 3 2 1",
        "expectedOutput": "1 2 3 4\n4"
      }
    ]
  },
  {
    "id": "cpp-ex-5-16",
    "title": "Multiset Count",
    "titleZh": "多重集合计数",
    "difficulty": "hard",
    "level": 5,
    "category": "STL Containers",
    "categoryZh": "STL容器",
    "tags": [
      "multiset",
      "count"
    ],
    "description": "Read n integers into a multiset, then read q queries. For each query value, print its count.\n\nInput: n, n integers, q, q query values\nOutput: count for each query, one per line",
    "descriptionZh": "读取n个整数到multiset，对每个查询输出出现次数。",
    "examples": [
      {
        "input": "7\n1 2 2 3 3 3 4\n3\n2 3 5",
        "output": "2\n3\n0"
      }
    ],
    "starterCode": "#include <iostream>\n#include <set>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    multiset<int> ms;\n    // TODO\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <set>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    multiset<int> ms;\n    for (int i = 0; i < n; i++) {\n        int x; cin >> x;\n        ms.insert(x);\n    }\n    int q; cin >> q;\n    while (q--) {\n        int x; cin >> x;\n        cout << ms.count(x) << endl;\n    }\n    return 0;\n}",
    "hints": [
      "multiset allows duplicates",
      "count() returns number of occurrences"
    ],
    "hintsZh": [
      "multiset允许重复",
      "count()返回出现次数"
    ],
    "testCases": [
      {
        "input": "7\n1 2 2 3 3 3 4\n3\n2 3 5",
        "expectedOutput": "2\n3\n0"
      },
      {
        "input": "3\n1 1 1\n1\n1",
        "expectedOutput": "3"
      },
      {
        "input": "4\n5 5 6 6\n2\n5 7",
        "expectedOutput": "2\n0"
      }
    ]
  },
  {
    "id": "cpp-ex-5-17",
    "title": "Stack - Valid Parentheses",
    "titleZh": "栈 - 有效括号",
    "difficulty": "hard",
    "level": 5,
    "category": "Stack",
    "categoryZh": "栈",
    "tags": [
      "stack",
      "parentheses",
      "matching"
    ],
    "description": "Read a string of parentheses ()[]{}. Determine if it is valid (every open bracket has matching close in correct order).\n\nInput: string\nOutput: YES or NO",
    "descriptionZh": "判断括号字符串是否有效。",
    "examples": [
      {
        "input": "({[]})",
        "output": "YES"
      }
    ],
    "starterCode": "#include <iostream>\n#include <stack>\n#include <string>\nusing namespace std;\n\nint main() {\n    string s; cin >> s;\n    // TODO: check valid parentheses\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <stack>\n#include <string>\nusing namespace std;\n\nint main() {\n    string s; cin >> s;\n    stack<char> st;\n    bool valid = true;\n    for (char c : s) {\n        if (c == '(' || c == '[' || c == '{') st.push(c);\n        else {\n            if (st.empty()) { valid = false; break; }\n            char top = st.top(); st.pop();\n            if ((c == ')' && top != '(') || (c == ']' && top != '[') || (c == '}' && top != '{')) {\n                valid = false; break;\n            }\n        }\n    }\n    if (!st.empty()) valid = false;\n    cout << (valid ? \"YES\" : \"NO\") << endl;\n    return 0;\n}",
    "hints": [
      "Push open brackets, pop on close",
      "Check matching pair when popping"
    ],
    "hintsZh": [
      "遇到开括号入栈，闭括号出栈",
      "出栈时检查是否匹配"
    ],
    "testCases": [
      {
        "input": "({[]})",
        "expectedOutput": "YES"
      },
      {
        "input": "([)]",
        "expectedOutput": "NO"
      },
      {
        "input": "()",
        "expectedOutput": "YES"
      },
      {
        "input": "{",
        "expectedOutput": "NO"
      },
      {
        "input": "()[]{}",
        "expectedOutput": "YES"
      }
    ]
  },
  {
    "id": "cpp-ex-5-18",
    "title": "Stack - Postfix Evaluation",
    "titleZh": "栈 - 后缀表达式求值",
    "difficulty": "hard",
    "level": 5,
    "category": "Stack",
    "categoryZh": "栈",
    "tags": [
      "stack",
      "postfix",
      "evaluation"
    ],
    "description": "Read a postfix expression (tokens separated by spaces). Evaluate and print the result. Operators: + - * /\n\nInput: postfix expression\nOutput: integer result",
    "descriptionZh": "计算后缀表达式的值。",
    "examples": [
      {
        "input": "3 4 + 2 *",
        "output": "14"
      }
    ],
    "starterCode": "#include <iostream>\n#include <stack>\n#include <string>\n#include <sstream>\nusing namespace std;\n\nint main() {\n    string line;\n    getline(cin, line);\n    // TODO: evaluate postfix\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <stack>\n#include <string>\n#include <sstream>\nusing namespace std;\n\nint main() {\n    string line;\n    getline(cin, line);\n    istringstream iss(line);\n    stack<int> st;\n    string token;\n    while (iss >> token) {\n        if (token == \"+\" || token == \"-\" || token == \"*\" || token == \"/\") {\n            int b = st.top(); st.pop();\n            int a = st.top(); st.pop();\n            if (token == \"+\") st.push(a + b);\n            else if (token == \"-\") st.push(a - b);\n            else if (token == \"*\") st.push(a * b);\n            else st.push(a / b);\n        } else {\n            st.push(stoi(token));\n        }\n    }\n    cout << st.top() << endl;\n    return 0;\n}",
    "hints": [
      "Numbers go on stack, operators pop two and push result",
      "Order matters: a op b where a is popped second"
    ],
    "hintsZh": [
      "数字入栈，运算符弹出两个计算后入栈",
      "注意顺序：先弹出的是b"
    ],
    "testCases": [
      {
        "input": "3 4 + 2 *",
        "expectedOutput": "14"
      },
      {
        "input": "5 1 2 + 4 * + 3 -",
        "expectedOutput": "14"
      },
      {
        "input": "2 3 +",
        "expectedOutput": "5"
      }
    ]
  },
  {
    "id": "cpp-ex-5-19",
    "title": "Min Stack",
    "titleZh": "最小栈",
    "difficulty": "hard",
    "level": 5,
    "category": "Stack",
    "categoryZh": "栈",
    "tags": [
      "stack",
      "min",
      "design"
    ],
    "description": "Implement a min stack supporting push, pop, and getMin in O(1). Read operations: \"push x\", \"pop\", \"min\". Print result of each \"min\".\n\nInput: n ops, then n lines of operations\nOutput: result of each min query",
    "descriptionZh": "实现O(1)获取最小值的栈。",
    "examples": [
      {
        "input": "5\npush 3\npush 1\nmin\npop\nmin",
        "output": "1\n3"
      }
    ],
    "starterCode": "#include <iostream>\n#include <stack>\n#include <string>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    stack<int> st, minSt;\n    // TODO\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <stack>\n#include <string>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    stack<int> st, minSt;\n    while (n--) {\n        string op; cin >> op;\n        if (op == \"push\") {\n            int x; cin >> x;\n            st.push(x);\n            if (minSt.empty() || x <= minSt.top()) minSt.push(x);\n        } else if (op == \"pop\") {\n            if (st.top() == minSt.top()) minSt.pop();\n            st.pop();\n        } else {\n            cout << minSt.top() << endl;\n        }\n    }\n    return 0;\n}",
    "hints": [
      "Use an auxiliary stack to track minimums",
      "Push to min stack when value <= current min"
    ],
    "hintsZh": [
      "用辅助栈跟踪最小值",
      "当值<=当前最小值时入辅助栈"
    ],
    "testCases": [
      {
        "input": "5\npush 3\npush 1\nmin\npop\nmin",
        "expectedOutput": "1\n3"
      },
      {
        "input": "4\npush 5\npush 5\npop\nmin",
        "expectedOutput": "5"
      },
      {
        "input": "3\npush 2\npush 0\nmin",
        "expectedOutput": "0"
      }
    ]
  },
  {
    "id": "cpp-ex-5-20",
    "title": "Queue BFS - Level Order",
    "titleZh": "队列BFS - 层序遍历",
    "difficulty": "hard",
    "level": 5,
    "category": "Queue",
    "categoryZh": "队列",
    "tags": [
      "queue",
      "bfs",
      "graph"
    ],
    "description": "Read an adjacency list of a graph (n nodes, m edges, 0-indexed). Perform BFS from node 0. Print visit order.\n\nInput: n m, then m edges (u v)\nOutput: BFS visit order space-separated",
    "descriptionZh": "读取图的邻接表，从节点0开始BFS，输出访问顺序。",
    "examples": [
      {
        "input": "4 4\n0 1\n0 2\n1 3\n2 3",
        "output": "0 1 2 3"
      }
    ],
    "starterCode": "#include <iostream>\n#include <vector>\n#include <queue>\nusing namespace std;\n\nint main() {\n    int n, m; cin >> n >> m;\n    vector<vector<int>> adj(n);\n    // TODO: read edges, BFS from 0\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <vector>\n#include <queue>\nusing namespace std;\n\nint main() {\n    int n, m; cin >> n >> m;\n    vector<vector<int>> adj(n);\n    for (int i = 0; i < m; i++) {\n        int u, v; cin >> u >> v;\n        adj[u].push_back(v);\n        adj[v].push_back(u);\n    }\n    vector<bool> visited(n, false);\n    queue<int> q;\n    q.push(0);\n    visited[0] = true;\n    bool first = true;\n    while (!q.empty()) {\n        int node = q.front(); q.pop();\n        if (!first) cout << \" \";\n        cout << node;\n        first = false;\n        for (int nb : adj[node]) {\n            if (!visited[nb]) {\n                visited[nb] = true;\n                q.push(nb);\n            }\n        }\n    }\n    cout << endl;\n    return 0;\n}",
    "hints": [
      "Use queue for BFS",
      "Mark visited before pushing"
    ],
    "hintsZh": [
      "用队列实现BFS",
      "入队前标记已访问"
    ],
    "testCases": [
      {
        "input": "4 4\n0 1\n0 2\n1 3\n2 3",
        "expectedOutput": "0 1 2 3"
      },
      {
        "input": "3 2\n0 1\n1 2",
        "expectedOutput": "0 1 2"
      },
      {
        "input": "2 1\n0 1",
        "expectedOutput": "0 1"
      }
    ]
  },
  {
    "id": "cpp-ex-5-21",
    "title": "Circular Queue",
    "titleZh": "循环队列",
    "difficulty": "hard",
    "level": 5,
    "category": "Queue",
    "categoryZh": "队列",
    "tags": [
      "queue",
      "circular",
      "array"
    ],
    "description": "Implement a circular queue of capacity k. Read operations: \"enqueue x\", \"dequeue\", \"front\". Print result of front queries or \"Empty\" if empty, \"Full\" if full on enqueue.\n\nInput: k n, then n operations\nOutput: results of front queries and error messages",
    "descriptionZh": "实现容量为k的循环队列。",
    "examples": [
      {
        "input": "3 5\nenqueue 1\nenqueue 2\nfront\ndequeue\nfront",
        "output": "1\n2"
      }
    ],
    "starterCode": "#include <iostream>\n#include <string>\nusing namespace std;\n\nint main() {\n    int k, n; cin >> k >> n;\n    int* arr = new int[k];\n    int head = 0, tail = 0, cnt = 0;\n    // TODO\n    delete[] arr;\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <string>\nusing namespace std;\n\nint main() {\n    int k, n; cin >> k >> n;\n    int* arr = new int[k];\n    int head = 0, tail = 0, cnt = 0;\n    while (n--) {\n        string op; cin >> op;\n        if (op == \"enqueue\") {\n            int x; cin >> x;\n            if (cnt == k) { cout << \"Full\" << endl; }\n            else { arr[tail] = x; tail = (tail + 1) % k; cnt++; }\n        } else if (op == \"dequeue\") {\n            if (cnt == 0) { cout << \"Empty\" << endl; }\n            else { head = (head + 1) % k; cnt--; }\n        } else {\n            if (cnt == 0) cout << \"Empty\" << endl;\n            else cout << arr[head] << endl;\n        }\n    }\n    delete[] arr;\n    return 0;\n}",
    "hints": [
      "Use modulo for wraparound",
      "Track count to distinguish full vs empty"
    ],
    "hintsZh": [
      "用取模实现循环",
      "用计数区分满和空"
    ],
    "testCases": [
      {
        "input": "3 5\nenqueue 1\nenqueue 2\nfront\ndequeue\nfront",
        "expectedOutput": "1\n2"
      },
      {
        "input": "2 4\nenqueue 1\nenqueue 2\nenqueue 3\nfront",
        "expectedOutput": "Full\n1"
      },
      {
        "input": "1 2\ndequeue\nfront",
        "expectedOutput": "Empty\nEmpty"
      }
    ]
  },
  {
    "id": "cpp-ex-5-22",
    "title": "Priority Queue - Kth Largest",
    "titleZh": "优先队列 - 第K大",
    "difficulty": "hard",
    "level": 5,
    "category": "STL Containers",
    "categoryZh": "STL容器",
    "tags": [
      "priority_queue",
      "heap",
      "kth-largest"
    ],
    "description": "Read n integers and k. Find the kth largest element using a min-heap of size k.\n\nInput: n k, then n integers\nOutput: kth largest",
    "descriptionZh": "用大小为k的最小堆找第k大元素。",
    "examples": [
      {
        "input": "6 2\n3 2 1 5 6 4",
        "output": "5"
      }
    ],
    "starterCode": "#include <iostream>\n#include <queue>\n#include <vector>\nusing namespace std;\n\nint main() {\n    int n, k; cin >> n >> k;\n    // TODO: use min-heap of size k\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <queue>\n#include <vector>\nusing namespace std;\n\nint main() {\n    int n, k; cin >> n >> k;\n    priority_queue<int, vector<int>, greater<int>> pq;\n    for (int i = 0; i < n; i++) {\n        int x; cin >> x;\n        pq.push(x);\n        if ((int)pq.size() > k) pq.pop();\n    }\n    cout << pq.top() << endl;\n    return 0;\n}",
    "hints": [
      "Min-heap: priority_queue<int, vector<int>, greater<int>>",
      "Keep only k elements"
    ],
    "hintsZh": [
      "最小堆: priority_queue<int, vector<int>, greater<int>>",
      "只保留k个元素"
    ],
    "testCases": [
      {
        "input": "6 2\n3 2 1 5 6 4",
        "expectedOutput": "5"
      },
      {
        "input": "5 1\n1 2 3 4 5",
        "expectedOutput": "5"
      },
      {
        "input": "4 4\n4 3 2 1",
        "expectedOutput": "1"
      }
    ]
  },
  {
    "id": "cpp-ex-5-23",
    "title": "Deque Sliding Window Max",
    "titleZh": "双端队列滑动窗口最大值",
    "difficulty": "hard",
    "level": 5,
    "category": "STL Containers",
    "categoryZh": "STL容器",
    "tags": [
      "deque",
      "sliding-window",
      "max"
    ],
    "description": "Read n integers and window size k. Find max in each sliding window of size k.\n\nInput: n k, then n integers\nOutput: max values space-separated",
    "descriptionZh": "找每个大小为k的滑动窗口的最大值。",
    "examples": [
      {
        "input": "8 3\n1 3 -1 -3 5 3 6 7",
        "output": "3 3 5 5 6 7"
      }
    ],
    "starterCode": "#include <iostream>\n#include <deque>\n#include <vector>\nusing namespace std;\n\nint main() {\n    int n, k; cin >> n >> k;\n    vector<int> nums(n);\n    for (int i = 0; i < n; i++) cin >> nums[i];\n    // TODO: sliding window max\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <deque>\n#include <vector>\nusing namespace std;\n\nint main() {\n    int n, k; cin >> n >> k;\n    vector<int> nums(n);\n    for (int i = 0; i < n; i++) cin >> nums[i];\n    deque<int> dq;\n    bool first = true;\n    for (int i = 0; i < n; i++) {\n        while (!dq.empty() && dq.front() <= i - k) dq.pop_front();\n        while (!dq.empty() && nums[dq.back()] <= nums[i]) dq.pop_back();\n        dq.push_back(i);\n        if (i >= k - 1) {\n            if (!first) cout << \" \";\n            cout << nums[dq.front()];\n            first = false;\n        }\n    }\n    cout << endl;\n    return 0;\n}",
    "hints": [
      "Store indices in deque, not values",
      "Remove from back if smaller, front if out of window"
    ],
    "hintsZh": [
      "在deque中存索引而非值",
      "从后端移除较小的，从前端移除超出窗口的"
    ],
    "testCases": [
      {
        "input": "8 3\n1 3 -1 -3 5 3 6 7",
        "expectedOutput": "3 3 5 5 6 7"
      },
      {
        "input": "4 2\n1 2 3 4",
        "expectedOutput": "2 3 4"
      },
      {
        "input": "3 1\n5 4 3",
        "expectedOutput": "5 4 3"
      }
    ]
  },
  {
    "id": "cpp-ex-5-24",
    "title": "Pair - Sort by Second",
    "titleZh": "Pair - 按第二元素排序",
    "difficulty": "hard",
    "level": 5,
    "category": "STL Containers",
    "categoryZh": "STL容器",
    "tags": [
      "pair",
      "sort",
      "custom-comparator"
    ],
    "description": "Read n pairs of (string, int). Sort by the integer value ascending. Print sorted pairs.\n\nInput: n, then n lines of name score\nOutput: sorted pairs, one per line",
    "descriptionZh": "读取n个(字符串,整数)对，按整数升序排序输出。",
    "examples": [
      {
        "input": "3\nAlice 90\nBob 70\nCarl 80",
        "output": "Bob 70\nCarl 80\nAlice 90"
      }
    ],
    "starterCode": "#include <iostream>\n#include <vector>\n#include <algorithm>\n#include <string>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    vector<pair<string,int>> v(n);\n    // TODO: read, sort by second, print\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <vector>\n#include <algorithm>\n#include <string>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    vector<pair<string,int>> v(n);\n    for (int i = 0; i < n; i++) cin >> v[i].first >> v[i].second;\n    sort(v.begin(), v.end(), [](const pair<string,int>& a, const pair<string,int>& b) {\n        return a.second < b.second;\n    });\n    for (auto& p : v) cout << p.first << \" \" << p.second << endl;\n    return 0;\n}",
    "hints": [
      "Use lambda as custom comparator",
      "Compare .second fields"
    ],
    "hintsZh": [
      "用lambda作为自定义比较器",
      "比较.second字段"
    ],
    "testCases": [
      {
        "input": "3\nAlice 90\nBob 70\nCarl 80",
        "expectedOutput": "Bob 70\nCarl 80\nAlice 90"
      },
      {
        "input": "2\nA 2\nB 1",
        "expectedOutput": "B 1\nA 2"
      },
      {
        "input": "1\nX 5",
        "expectedOutput": "X 5"
      }
    ]
  },
  {
    "id": "cpp-ex-5-25",
    "title": "Tuple Unpacking",
    "titleZh": "元组解包",
    "difficulty": "hard",
    "level": 5,
    "category": "STL Containers",
    "categoryZh": "STL容器",
    "tags": [
      "tuple",
      "structured-bindings"
    ],
    "description": "Read name, age, gpa. Store in a tuple, then extract using get<> and print.\n\nInput: name age gpa\nOutput: Name: name Age: age GPA: gpa",
    "descriptionZh": "读取信息存入tuple，用get<>提取并输出。",
    "examples": [
      {
        "input": "Alice 20 3.8",
        "output": "Name: Alice Age: 20 GPA: 3.8"
      }
    ],
    "starterCode": "#include <iostream>\n#include <tuple>\n#include <string>\n#include <iomanip>\nusing namespace std;\n\nint main() {\n    string name; int age; double gpa;\n    cin >> name >> age >> gpa;\n    // TODO: store in tuple, extract and print\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <tuple>\n#include <string>\n#include <iomanip>\nusing namespace std;\n\nint main() {\n    string name; int age; double gpa;\n    cin >> name >> age >> gpa;\n    auto t = make_tuple(name, age, gpa);\n    cout << \"Name: \" << get<0>(t) << \" Age: \" << get<1>(t) << \" GPA: \" << fixed << setprecision(1) << get<2>(t) << endl;\n    return 0;\n}",
    "hints": [
      "Use make_tuple to create",
      "get<index>(tuple) to access"
    ],
    "hintsZh": [
      "用make_tuple创建",
      "用get<索引>(tuple)访问"
    ],
    "testCases": [
      {
        "input": "Alice 20 3.8",
        "expectedOutput": "Name: Alice Age: 20 GPA: 3.8"
      },
      {
        "input": "Bob 25 4.0",
        "expectedOutput": "Name: Bob Age: 25 GPA: 4.0"
      }
    ]
  },
  {
    "id": "cpp-ex-5-26",
    "title": "Iterator - Custom Traverse",
    "titleZh": "迭代器 - 自定义遍历",
    "difficulty": "hard",
    "level": 5,
    "category": "Iterators",
    "categoryZh": "迭代器",
    "tags": [
      "iterator",
      "vector",
      "reverse"
    ],
    "description": "Read n integers into a vector. Print them in reverse using reverse iterators.\n\nInput: n, n integers\nOutput: reversed, space-separated",
    "descriptionZh": "读取n个整数，用反向迭代器逆序输出。",
    "examples": [
      {
        "input": "4\n1 2 3 4",
        "output": "4 3 2 1"
      }
    ],
    "starterCode": "#include <iostream>\n#include <vector>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    vector<int> v(n);\n    for (int i = 0; i < n; i++) cin >> v[i];\n    // TODO: use rbegin/rend\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <vector>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    vector<int> v(n);\n    for (int i = 0; i < n; i++) cin >> v[i];\n    bool first = true;\n    for (auto it = v.rbegin(); it != v.rend(); ++it) {\n        if (!first) cout << \" \";\n        cout << *it;\n        first = false;\n    }\n    cout << endl;\n    return 0;\n}",
    "hints": [
      "rbegin() points to last element",
      "rend() points before first"
    ],
    "hintsZh": [
      "rbegin()指向最后一个元素",
      "rend()指向第一个元素之前"
    ],
    "testCases": [
      {
        "input": "4\n1 2 3 4",
        "expectedOutput": "4 3 2 1"
      },
      {
        "input": "1\n5",
        "expectedOutput": "5"
      },
      {
        "input": "3\n10 20 30",
        "expectedOutput": "30 20 10"
      }
    ]
  },
  {
    "id": "cpp-ex-5-27",
    "title": "STL Sort with Lambda",
    "titleZh": "STL排序与Lambda",
    "difficulty": "hard",
    "level": 5,
    "category": "STL Algorithms",
    "categoryZh": "STL算法",
    "tags": [
      "sort",
      "lambda",
      "descending"
    ],
    "description": "Read n integers. Sort in descending order using sort with a lambda. Print result.\n\nInput: n, n integers\nOutput: sorted descending, space-separated",
    "descriptionZh": "读取n个整数，用lambda降序排序输出。",
    "examples": [
      {
        "input": "5\n3 1 4 1 5",
        "output": "5 4 3 1 1"
      }
    ],
    "starterCode": "#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    vector<int> v(n);\n    for (int i = 0; i < n; i++) cin >> v[i];\n    // TODO: sort descending with lambda\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    vector<int> v(n);\n    for (int i = 0; i < n; i++) cin >> v[i];\n    sort(v.begin(), v.end(), [](int a, int b) { return a > b; });\n    for (int i = 0; i < n; i++) {\n        if (i) cout << \" \";\n        cout << v[i];\n    }\n    cout << endl;\n    return 0;\n}",
    "hints": [
      "Lambda: [](int a, int b) { return a > b; }",
      "sort takes begin, end, comparator"
    ],
    "hintsZh": [
      "Lambda: [](int a, int b) { return a > b; }",
      "sort接受begin, end, 比较器"
    ],
    "testCases": [
      {
        "input": "5\n3 1 4 1 5",
        "expectedOutput": "5 4 3 1 1"
      },
      {
        "input": "3\n1 2 3",
        "expectedOutput": "3 2 1"
      },
      {
        "input": "1\n7",
        "expectedOutput": "7"
      }
    ]
  },
  {
    "id": "cpp-ex-5-28",
    "title": "Binary Search",
    "titleZh": "二分查找",
    "difficulty": "hard",
    "level": 5,
    "category": "STL Algorithms",
    "categoryZh": "STL算法",
    "tags": [
      "binary_search",
      "lower_bound",
      "upper_bound"
    ],
    "description": "Read n sorted integers and q queries. For each query, print \"Found\" if it exists (binary_search), and its lower_bound position.\n\nInput: n, n sorted ints, q, q queries\nOutput: for each: \"Found at pos\" or \"Not found, insert at pos\"",
    "descriptionZh": "对排序数组执行二分查找和lower_bound。",
    "examples": [
      {
        "input": "5\n1 3 5 7 9\n2\n5\n4",
        "output": "Found at 2\nNot found, insert at 2"
      }
    ],
    "starterCode": "#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    vector<int> v(n);\n    for (int i = 0; i < n; i++) cin >> v[i];\n    int q; cin >> q;\n    // TODO\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    vector<int> v(n);\n    for (int i = 0; i < n; i++) cin >> v[i];\n    int q; cin >> q;\n    while (q--) {\n        int x; cin >> x;\n        auto it = lower_bound(v.begin(), v.end(), x);\n        int pos = it - v.begin();\n        if (binary_search(v.begin(), v.end(), x)) {\n            cout << \"Found at \" << pos << endl;\n        } else {\n            cout << \"Not found, insert at \" << pos << endl;\n        }\n    }\n    return 0;\n}",
    "hints": [
      "binary_search returns bool",
      "lower_bound returns iterator to first >= x"
    ],
    "hintsZh": [
      "binary_search返回bool",
      "lower_bound返回第一个>=x的迭代器"
    ],
    "testCases": [
      {
        "input": "5\n1 3 5 7 9\n2\n5\n4",
        "expectedOutput": "Found at 2\nNot found, insert at 2"
      },
      {
        "input": "3\n1 2 3\n1\n1",
        "expectedOutput": "Found at 0"
      },
      {
        "input": "3\n1 2 3\n1\n10",
        "expectedOutput": "Not found, insert at 3"
      }
    ]
  },
  {
    "id": "cpp-ex-5-29",
    "title": "Accumulate & Transform",
    "titleZh": "累加与变换",
    "difficulty": "hard",
    "level": 5,
    "category": "STL Algorithms",
    "categoryZh": "STL算法",
    "tags": [
      "accumulate",
      "transform",
      "numeric"
    ],
    "description": "Read n integers. Print their sum using accumulate, then print the vector with each element doubled using transform.\n\nInput: n, n integers\nOutput: line 1: sum, line 2: doubled values",
    "descriptionZh": "用accumulate求和，用transform将每个元素翻倍。",
    "examples": [
      {
        "input": "4\n1 2 3 4",
        "output": "10\n2 4 6 8"
      }
    ],
    "starterCode": "#include <iostream>\n#include <vector>\n#include <algorithm>\n#include <numeric>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    vector<int> v(n);\n    for (int i = 0; i < n; i++) cin >> v[i];\n    // TODO\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <vector>\n#include <algorithm>\n#include <numeric>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    vector<int> v(n);\n    for (int i = 0; i < n; i++) cin >> v[i];\n    cout << accumulate(v.begin(), v.end(), 0) << endl;\n    transform(v.begin(), v.end(), v.begin(), [](int x) { return x * 2; });\n    for (int i = 0; i < n; i++) {\n        if (i) cout << \" \";\n        cout << v[i];\n    }\n    cout << endl;\n    return 0;\n}",
    "hints": [
      "accumulate(begin, end, initial_value)",
      "transform can write back to same container"
    ],
    "hintsZh": [
      "accumulate(begin, end, 初始值)",
      "transform可以写回同一容器"
    ],
    "testCases": [
      {
        "input": "4\n1 2 3 4",
        "expectedOutput": "10\n2 4 6 8"
      },
      {
        "input": "3\n0 0 0",
        "expectedOutput": "0\n0 0 0"
      },
      {
        "input": "2\n-1 1",
        "expectedOutput": "0\n-2 2"
      }
    ]
  },
  {
    "id": "cpp-ex-5-30",
    "title": "Count If & Remove If",
    "titleZh": "条件计数与条件移除",
    "difficulty": "hard",
    "level": 5,
    "category": "STL Algorithms",
    "categoryZh": "STL算法",
    "tags": [
      "count_if",
      "remove_if",
      "erase"
    ],
    "description": "Read n integers. Print count of even numbers using count_if. Then remove all even numbers and print remaining.\n\nInput: n, n integers\nOutput: line 1: count of evens, line 2: remaining odds",
    "descriptionZh": "用count_if统计偶数个数，remove_if移除偶数后输出。",
    "examples": [
      {
        "input": "5\n1 2 3 4 5",
        "output": "2\n1 3 5"
      }
    ],
    "starterCode": "#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    vector<int> v(n);\n    for (int i = 0; i < n; i++) cin >> v[i];\n    // TODO\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    vector<int> v(n);\n    for (int i = 0; i < n; i++) cin >> v[i];\n    int cnt = count_if(v.begin(), v.end(), [](int x) { return x % 2 == 0; });\n    cout << cnt << endl;\n    v.erase(remove_if(v.begin(), v.end(), [](int x) { return x % 2 == 0; }), v.end());\n    for (int i = 0; i < (int)v.size(); i++) {\n        if (i) cout << \" \";\n        cout << v[i];\n    }\n    cout << endl;\n    return 0;\n}",
    "hints": [
      "remove_if moves elements but does not resize",
      "Use erase-remove idiom"
    ],
    "hintsZh": [
      "remove_if移动元素但不改变大小",
      "使用erase-remove惯用法"
    ],
    "testCases": [
      {
        "input": "5\n1 2 3 4 5",
        "expectedOutput": "2\n1 3 5"
      },
      {
        "input": "4\n2 4 6 8",
        "expectedOutput": "4\n"
      },
      {
        "input": "3\n1 3 5",
        "expectedOutput": "0\n1 3 5"
      }
    ]
  },
  {
    "id": "cpp-ex-5-31",
    "title": "Unique Elements",
    "titleZh": "去除连续重复",
    "difficulty": "hard",
    "level": 5,
    "category": "STL Algorithms",
    "categoryZh": "STL算法",
    "tags": [
      "unique",
      "sort",
      "erase"
    ],
    "description": "Read n integers. Remove all duplicates (sort first, then unique + erase). Print result.\n\nInput: n, n integers\nOutput: sorted unique elements",
    "descriptionZh": "排序后去重输出。",
    "examples": [
      {
        "input": "7\n3 1 4 1 5 9 3",
        "output": "1 3 4 5 9"
      }
    ],
    "starterCode": "#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    vector<int> v(n);\n    for (int i = 0; i < n; i++) cin >> v[i];\n    // TODO: sort, unique, erase\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    vector<int> v(n);\n    for (int i = 0; i < n; i++) cin >> v[i];\n    sort(v.begin(), v.end());\n    v.erase(unique(v.begin(), v.end()), v.end());\n    for (int i = 0; i < (int)v.size(); i++) {\n        if (i) cout << \" \";\n        cout << v[i];\n    }\n    cout << endl;\n    return 0;\n}",
    "hints": [
      "Sort before calling unique",
      "unique only removes consecutive duplicates"
    ],
    "hintsZh": [
      "调用unique前先排序",
      "unique只移除连续重复"
    ],
    "testCases": [
      {
        "input": "7\n3 1 4 1 5 9 3",
        "expectedOutput": "1 3 4 5 9"
      },
      {
        "input": "3\n1 1 1",
        "expectedOutput": "1"
      },
      {
        "input": "4\n4 3 2 1",
        "expectedOutput": "1 2 3 4"
      }
    ]
  },
  {
    "id": "cpp-ex-5-32",
    "title": "Merge Sorted Arrays",
    "titleZh": "合并有序数组",
    "difficulty": "hard",
    "level": 5,
    "category": "STL Algorithms",
    "categoryZh": "STL算法",
    "tags": [
      "merge",
      "sorted",
      "algorithm"
    ],
    "description": "Read two sorted arrays. Merge them into one sorted array using std::merge. Print result.\n\nInput: n, n sorted ints, m, m sorted ints\nOutput: merged sorted array",
    "descriptionZh": "用std::merge合并两个有序数组。",
    "examples": [
      {
        "input": "3\n1 3 5\n3\n2 4 6",
        "output": "1 2 3 4 5 6"
      }
    ],
    "starterCode": "#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    vector<int> a(n);\n    for (int i = 0; i < n; i++) cin >> a[i];\n    int m; cin >> m;\n    vector<int> b(m);\n    for (int i = 0; i < m; i++) cin >> b[i];\n    // TODO: merge\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    vector<int> a(n);\n    for (int i = 0; i < n; i++) cin >> a[i];\n    int m; cin >> m;\n    vector<int> b(m);\n    for (int i = 0; i < m; i++) cin >> b[i];\n    vector<int> result(n + m);\n    merge(a.begin(), a.end(), b.begin(), b.end(), result.begin());\n    for (int i = 0; i < (int)result.size(); i++) {\n        if (i) cout << \" \";\n        cout << result[i];\n    }\n    cout << endl;\n    return 0;\n}",
    "hints": [
      "Both arrays must be sorted",
      "Result vector must have enough space"
    ],
    "hintsZh": [
      "两个数组必须已排序",
      "结果向量需要足够空间"
    ],
    "testCases": [
      {
        "input": "3\n1 3 5\n3\n2 4 6",
        "expectedOutput": "1 2 3 4 5 6"
      },
      {
        "input": "2\n1 2\n2\n3 4",
        "expectedOutput": "1 2 3 4"
      },
      {
        "input": "1\n5\n1\n3",
        "expectedOutput": "3 5"
      }
    ]
  },
  {
    "id": "cpp-ex-5-33",
    "title": "Custom Comparator Sort",
    "titleZh": "自定义比较器排序",
    "difficulty": "hard",
    "level": 5,
    "category": "STL Algorithms",
    "categoryZh": "STL算法",
    "tags": [
      "sort",
      "comparator",
      "struct"
    ],
    "description": "Read n students (name score). Sort by score descending; if equal, by name ascending. Print sorted list.\n\nInput: n, then n lines of name score\nOutput: sorted list",
    "descriptionZh": "按分数降序排序，相同分数按姓名升序。",
    "examples": [
      {
        "input": "3\nAlice 90\nBob 90\nCarl 80",
        "output": "Alice 90\nBob 90\nCarl 80"
      }
    ],
    "starterCode": "#include <iostream>\n#include <vector>\n#include <algorithm>\n#include <string>\nusing namespace std;\n\nstruct Student { string name; int score; };\n\nint main() {\n    int n; cin >> n;\n    vector<Student> v(n);\n    for (int i = 0; i < n; i++) cin >> v[i].name >> v[i].score;\n    // TODO: sort with custom comparator\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <vector>\n#include <algorithm>\n#include <string>\nusing namespace std;\n\nstruct Student { string name; int score; };\n\nint main() {\n    int n; cin >> n;\n    vector<Student> v(n);\n    for (int i = 0; i < n; i++) cin >> v[i].name >> v[i].score;\n    sort(v.begin(), v.end(), [](const Student& a, const Student& b) {\n        if (a.score != b.score) return a.score > b.score;\n        return a.name < b.name;\n    });\n    for (auto& s : v) cout << s.name << \" \" << s.score << endl;\n    return 0;\n}",
    "hints": [
      "Compare scores first, then names",
      "Return true if a should come before b"
    ],
    "hintsZh": [
      "先比较分数，再比较姓名",
      "如果a应在b前面则返回true"
    ],
    "testCases": [
      {
        "input": "3\nAlice 90\nBob 90\nCarl 80",
        "expectedOutput": "Alice 90\nBob 90\nCarl 80"
      },
      {
        "input": "2\nZara 50\nAmy 50",
        "expectedOutput": "Amy 50\nZara 50"
      },
      {
        "input": "3\nA 100\nB 80\nC 90",
        "expectedOutput": "A 100\nC 90\nB 80"
      }
    ]
  },
  {
    "id": "cpp-ex-5-34",
    "title": "Auto & Range-For",
    "titleZh": "Auto与范围For",
    "difficulty": "hard",
    "level": 5,
    "category": "Modern C++",
    "categoryZh": "现代C++",
    "tags": [
      "auto",
      "range-for",
      "map"
    ],
    "description": "Read n key-value pairs (string int) into a map. Use auto and range-for to print all entries.\n\nInput: n, then n key value pairs\nOutput: key: value (sorted by key)",
    "descriptionZh": "用auto和范围for遍历map输出。",
    "examples": [
      {
        "input": "3\na 1\nb 2\nc 3",
        "output": "a: 1\nb: 2\nc: 3"
      }
    ],
    "starterCode": "#include <iostream>\n#include <map>\n#include <string>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    map<string, int> m;\n    // TODO: read and print with auto + range-for\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <map>\n#include <string>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    map<string, int> m;\n    for (int i = 0; i < n; i++) {\n        string k; int v;\n        cin >> k >> v;\n        m[k] = v;\n    }\n    for (const auto& [key, val] : m) {\n        cout << key << \": \" << val << endl;\n    }\n    return 0;\n}",
    "hints": [
      "auto deduces the type",
      "Structured bindings: auto& [k, v]"
    ],
    "hintsZh": [
      "auto推导类型",
      "结构化绑定: auto& [k, v]"
    ],
    "testCases": [
      {
        "input": "3\na 1\nb 2\nc 3",
        "expectedOutput": "a: 1\nb: 2\nc: 3"
      },
      {
        "input": "2\nz 26\na 1",
        "expectedOutput": "a: 1\nz: 26"
      },
      {
        "input": "1\nhello 42",
        "expectedOutput": "hello: 42"
      }
    ]
  },
  {
    "id": "cpp-ex-5-35",
    "title": "Lambda Capture",
    "titleZh": "Lambda捕获",
    "difficulty": "hard",
    "level": 5,
    "category": "Modern C++",
    "categoryZh": "现代C++",
    "tags": [
      "lambda",
      "capture",
      "functional"
    ],
    "description": "Read n integers and a threshold t. Use count_if with a lambda that captures t to count elements > t.\n\nInput: n, n integers, t\nOutput: count of elements > t",
    "descriptionZh": "用lambda捕获阈值t，统计大于t的元素个数。",
    "examples": [
      {
        "input": "5\n1 2 3 4 5\n3",
        "output": "2"
      }
    ],
    "starterCode": "#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    vector<int> v(n);\n    for (int i = 0; i < n; i++) cin >> v[i];\n    int t; cin >> t;\n    // TODO: count_if with lambda capturing t\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    vector<int> v(n);\n    for (int i = 0; i < n; i++) cin >> v[i];\n    int t; cin >> t;\n    int cnt = count_if(v.begin(), v.end(), [t](int x) { return x > t; });\n    cout << cnt << endl;\n    return 0;\n}",
    "hints": [
      "[t] captures t by value",
      "Lambda: [capture](params) { body }"
    ],
    "hintsZh": [
      "[t]按值捕获t",
      "Lambda: [捕获](参数) { 函数体 }"
    ],
    "testCases": [
      {
        "input": "5\n1 2 3 4 5\n3",
        "expectedOutput": "2"
      },
      {
        "input": "4\n10 20 30 40\n25",
        "expectedOutput": "2"
      },
      {
        "input": "3\n1 1 1\n0",
        "expectedOutput": "3"
      }
    ]
  },
  {
    "id": "cpp-ex-5-36",
    "title": "Unique Pointer",
    "titleZh": "独占指针",
    "difficulty": "hard",
    "level": 5,
    "category": "Smart Pointers",
    "categoryZh": "智能指针",
    "tags": [
      "unique_ptr",
      "smart-pointer",
      "memory"
    ],
    "description": "Read n integers. Create a unique_ptr to a dynamically allocated array. Print sum and elements.\n\nInput: n, n integers\nOutput: line 1: sum, line 2: elements",
    "descriptionZh": "用unique_ptr管理动态数组，输出和与元素。",
    "examples": [
      {
        "input": "3\n1 2 3",
        "output": "6\n1 2 3"
      }
    ],
    "starterCode": "#include <iostream>\n#include <memory>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    // TODO: use unique_ptr\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <memory>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    auto arr = make_unique<int[]>(n);\n    int sum = 0;\n    for (int i = 0; i < n; i++) {\n        cin >> arr[i];\n        sum += arr[i];\n    }\n    cout << sum << endl;\n    for (int i = 0; i < n; i++) {\n        if (i) cout << \" \";\n        cout << arr[i];\n    }\n    cout << endl;\n    return 0;\n}",
    "hints": [
      "make_unique<int[]>(n) for arrays",
      "No need for delete - automatic cleanup"
    ],
    "hintsZh": [
      "make_unique<int[]>(n)创建数组",
      "不需要delete - 自动清理"
    ],
    "testCases": [
      {
        "input": "3\n1 2 3",
        "expectedOutput": "6\n1 2 3"
      },
      {
        "input": "1\n10",
        "expectedOutput": "10\n10"
      },
      {
        "input": "4\n-1 -2 3 4",
        "expectedOutput": "4\n-1 -2 3 4"
      }
    ]
  },
  {
    "id": "cpp-ex-5-37",
    "title": "Shared Pointer",
    "titleZh": "共享指针",
    "difficulty": "hard",
    "level": 5,
    "category": "Smart Pointers",
    "categoryZh": "智能指针",
    "tags": [
      "shared_ptr",
      "smart-pointer",
      "reference-count"
    ],
    "description": "Create a shared_ptr to an int. Copy it. Print value and use_count at each step.\n\nInput: an integer\nOutput: value, count after create, count after copy, count after reset",
    "descriptionZh": "创建shared_ptr并拷贝，输出引用计数。",
    "examples": [
      {
        "input": "42",
        "output": "42\n1\n2\n1"
      }
    ],
    "starterCode": "#include <iostream>\n#include <memory>\nusing namespace std;\n\nint main() {\n    int x; cin >> x;\n    // TODO: shared_ptr demo\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <memory>\nusing namespace std;\n\nint main() {\n    int x; cin >> x;\n    auto sp1 = make_shared<int>(x);\n    cout << *sp1 << endl;\n    cout << sp1.use_count() << endl;\n    auto sp2 = sp1;\n    cout << sp1.use_count() << endl;\n    sp2.reset();\n    cout << sp1.use_count() << endl;\n    return 0;\n}",
    "hints": [
      "use_count() shows reference count",
      "reset() releases ownership"
    ],
    "hintsZh": [
      "use_count()显示引用计数",
      "reset()释放所有权"
    ],
    "testCases": [
      {
        "input": "42",
        "expectedOutput": "42\n1\n2\n1"
      },
      {
        "input": "0",
        "expectedOutput": "0\n1\n2\n1"
      },
      {
        "input": "-5",
        "expectedOutput": "-5\n1\n2\n1"
      }
    ]
  },
  {
    "id": "cpp-ex-5-38",
    "title": "Move Semantics",
    "titleZh": "移动语义",
    "difficulty": "hard",
    "level": 5,
    "category": "Modern C++",
    "categoryZh": "现代C++",
    "tags": [
      "move",
      "rvalue",
      "vector"
    ],
    "description": "Create a vector of strings. Move a string into the vector using std::move. Print the vector contents and whether original is empty.\n\nInput: a string\nOutput: line 1: vector content, line 2: \"empty\" or \"not empty\"",
    "descriptionZh": "用std::move将字符串移入vector，检查原字符串状态。",
    "examples": [
      {
        "input": "hello",
        "output": "hello\nempty"
      }
    ],
    "starterCode": "#include <iostream>\n#include <vector>\n#include <string>\nusing namespace std;\n\nint main() {\n    string s; cin >> s;\n    vector<string> v;\n    // TODO: use std::move\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <vector>\n#include <string>\nusing namespace std;\n\nint main() {\n    string s; cin >> s;\n    vector<string> v;\n    v.push_back(std::move(s));\n    cout << v[0] << endl;\n    cout << (s.empty() ? \"empty\" : \"not empty\") << endl;\n    return 0;\n}",
    "hints": [
      "std::move casts to rvalue reference",
      "After move, original is in valid but unspecified state"
    ],
    "hintsZh": [
      "std::move转换为右值引用",
      "移动后原对象处于有效但未指定状态"
    ],
    "testCases": [
      {
        "input": "hello",
        "expectedOutput": "hello\nempty"
      },
      {
        "input": "world",
        "expectedOutput": "world\nempty"
      },
      {
        "input": "test",
        "expectedOutput": "test\nempty"
      }
    ]
  },
  {
    "id": "cpp-ex-5-39",
    "title": "Merge Two Sorted Lists",
    "titleZh": "合并两个有序链表",
    "difficulty": "hard",
    "level": 5,
    "category": "Classic Problems",
    "categoryZh": "经典问题",
    "tags": [
      "linked-list",
      "merge",
      "sorted"
    ],
    "description": "Read two sorted linked lists. Merge them into one sorted list. Print result.\n\nInput: n, n sorted ints, m, m sorted ints\nOutput: merged sorted list \"v1 -> v2 -> ... -> NULL\"",
    "descriptionZh": "合并两个有序链表。",
    "examples": [
      {
        "input": "3\n1 3 5\n3\n2 4 6",
        "output": "1 -> 2 -> 3 -> 4 -> 5 -> 6 -> NULL"
      }
    ],
    "starterCode": "#include <iostream>\nusing namespace std;\n\nstruct Node {\n    int val;\n    Node* next;\n    Node(int v) : val(v), next(nullptr) {}\n};\n\nNode* buildList(int n) {\n    Node* head = nullptr, *tail = nullptr;\n    for (int i = 0; i < n; i++) {\n        int v; cin >> v;\n        Node* nd = new Node(v);\n        if (!head) head = tail = nd;\n        else { tail->next = nd; tail = nd; }\n    }\n    return head;\n}\n\n// TODO: Node* mergeLists(Node* l1, Node* l2)\n\nint main() {\n    int n; cin >> n;\n    Node* l1 = buildList(n);\n    int m; cin >> m;\n    Node* l2 = buildList(m);\n    Node* merged = mergeLists(l1, l2);\n    Node* c = merged;\n    while (c) { cout << c->val << \" -> \"; c = c->next; }\n    cout << \"NULL\" << endl;\n    return 0;\n}",
    "solution": "#include <iostream>\nusing namespace std;\n\nstruct Node {\n    int val;\n    Node* next;\n    Node(int v) : val(v), next(nullptr) {}\n};\n\nNode* buildList(int n) {\n    Node* head = nullptr, *tail = nullptr;\n    for (int i = 0; i < n; i++) {\n        int v; cin >> v;\n        Node* nd = new Node(v);\n        if (!head) head = tail = nd;\n        else { tail->next = nd; tail = nd; }\n    }\n    return head;\n}\n\nNode* mergeLists(Node* l1, Node* l2) {\n    Node dummy(0);\n    Node* tail = &dummy;\n    while (l1 && l2) {\n        if (l1->val <= l2->val) { tail->next = l1; l1 = l1->next; }\n        else { tail->next = l2; l2 = l2->next; }\n        tail = tail->next;\n    }\n    tail->next = l1 ? l1 : l2;\n    return dummy.next;\n}\n\nint main() {\n    int n; cin >> n;\n    Node* l1 = buildList(n);\n    int m; cin >> m;\n    Node* l2 = buildList(m);\n    Node* merged = mergeLists(l1, l2);\n    Node* c = merged;\n    while (c) { cout << c->val << \" -> \"; c = c->next; }\n    cout << \"NULL\" << endl;\n    return 0;\n}",
    "hints": [
      "Use a dummy head node",
      "Attach remaining list at the end"
    ],
    "hintsZh": [
      "使用哑头节点",
      "将剩余链表接在末尾"
    ],
    "testCases": [
      {
        "input": "3\n1 3 5\n3\n2 4 6",
        "expectedOutput": "1 -> 2 -> 3 -> 4 -> 5 -> 6 -> NULL"
      },
      {
        "input": "2\n1 2\n2\n3 4",
        "expectedOutput": "1 -> 2 -> 3 -> 4 -> NULL"
      },
      {
        "input": "1\n5\n1\n3",
        "expectedOutput": "3 -> 5 -> NULL"
      }
    ]
  },
  {
    "id": "cpp-ex-5-40",
    "title": "Reverse Linked List",
    "titleZh": "反转链表",
    "difficulty": "hard",
    "level": 5,
    "category": "Classic Problems",
    "categoryZh": "经典问题",
    "tags": [
      "linked-list",
      "reverse",
      "iterative"
    ],
    "description": "Read n integers into a linked list, reverse it iteratively, print result.\n\nInput: n, n integers\nOutput: reversed list \"v1 -> v2 -> ... -> NULL\"",
    "descriptionZh": "迭代反转链表。",
    "examples": [
      {
        "input": "4\n1 2 3 4",
        "output": "4 -> 3 -> 2 -> 1 -> NULL"
      }
    ],
    "starterCode": "#include <iostream>\nusing namespace std;\n\nstruct Node {\n    int val;\n    Node* next;\n    Node(int v) : val(v), next(nullptr) {}\n};\n\nNode* reverseList(Node* head) {\n    // TODO\n}\n\nint main() {\n    int n; cin >> n;\n    Node* head = nullptr, *tail = nullptr;\n    for (int i = 0; i < n; i++) {\n        int v; cin >> v;\n        Node* nd = new Node(v);\n        if (!head) head = tail = nd;\n        else { tail->next = nd; tail = nd; }\n    }\n    head = reverseList(head);\n    Node* c = head;\n    while (c) { cout << c->val << \" -> \"; c = c->next; }\n    cout << \"NULL\" << endl;\n    return 0;\n}",
    "solution": "#include <iostream>\nusing namespace std;\n\nstruct Node {\n    int val;\n    Node* next;\n    Node(int v) : val(v), next(nullptr) {}\n};\n\nNode* reverseList(Node* head) {\n    Node* prev = nullptr;\n    Node* curr = head;\n    while (curr) {\n        Node* next = curr->next;\n        curr->next = prev;\n        prev = curr;\n        curr = next;\n    }\n    return prev;\n}\n\nint main() {\n    int n; cin >> n;\n    Node* head = nullptr, *tail = nullptr;\n    for (int i = 0; i < n; i++) {\n        int v; cin >> v;\n        Node* nd = new Node(v);\n        if (!head) head = tail = nd;\n        else { tail->next = nd; tail = nd; }\n    }\n    head = reverseList(head);\n    Node* c = head;\n    while (c) { cout << c->val << \" -> \"; c = c->next; }\n    cout << \"NULL\" << endl;\n    return 0;\n}",
    "hints": [
      "Three pointers: prev, curr, next",
      "Return prev when curr is null"
    ],
    "hintsZh": [
      "三个指针：prev, curr, next",
      "curr为空时返回prev"
    ],
    "testCases": [
      {
        "input": "4\n1 2 3 4",
        "expectedOutput": "4 -> 3 -> 2 -> 1 -> NULL"
      },
      {
        "input": "1\n5",
        "expectedOutput": "5 -> NULL"
      },
      {
        "input": "3\n10 20 30",
        "expectedOutput": "30 -> 20 -> 10 -> NULL"
      }
    ]
  },
  {
    "id": "cpp-ex-5-41",
    "title": "BST Insert & Inorder",
    "titleZh": "BST插入与中序遍历",
    "difficulty": "hard",
    "level": 5,
    "category": "Classic Problems",
    "categoryZh": "经典问题",
    "tags": [
      "bst",
      "tree",
      "inorder"
    ],
    "description": "Read n integers. Insert each into a BST. Print inorder traversal (which gives sorted order).\n\nInput: n, n integers\nOutput: sorted elements space-separated",
    "descriptionZh": "构建BST并中序遍历输出。",
    "examples": [
      {
        "input": "5\n5 3 7 1 4",
        "output": "1 3 4 5 7"
      }
    ],
    "starterCode": "#include <iostream>\nusing namespace std;\n\nstruct Node {\n    int val;\n    Node *left, *right;\n    Node(int v) : val(v), left(nullptr), right(nullptr) {}\n};\n\n// TODO: insert and inorder\n\nint main() {\n    int n; cin >> n;\n    Node* root = nullptr;\n    for (int i = 0; i < n; i++) {\n        int v; cin >> v;\n        root = insert(root, v);\n    }\n    inorder(root);\n    cout << endl;\n    return 0;\n}",
    "solution": "#include <iostream>\nusing namespace std;\n\nstruct Node {\n    int val;\n    Node *left, *right;\n    Node(int v) : val(v), left(nullptr), right(nullptr) {}\n};\n\nNode* insert(Node* root, int val) {\n    if (!root) return new Node(val);\n    if (val < root->val) root->left = insert(root->left, val);\n    else root->right = insert(root->right, val);\n    return root;\n}\n\nbool first_print = true;\nvoid inorder(Node* root) {\n    if (!root) return;\n    inorder(root->left);\n    if (!first_print) cout << \" \";\n    cout << root->val;\n    first_print = false;\n    inorder(root->right);\n}\n\nint main() {\n    int n; cin >> n;\n    Node* root = nullptr;\n    for (int i = 0; i < n; i++) {\n        int v; cin >> v;\n        root = insert(root, v);\n    }\n    inorder(root);\n    cout << endl;\n    return 0;\n}",
    "hints": [
      "Recursively go left for smaller, right for larger",
      "Inorder: left, root, right"
    ],
    "hintsZh": [
      "递归：小的往左，大的往右",
      "中序：左、根、右"
    ],
    "testCases": [
      {
        "input": "5\n5 3 7 1 4",
        "expectedOutput": "1 3 4 5 7"
      },
      {
        "input": "3\n3 1 2",
        "expectedOutput": "1 2 3"
      },
      {
        "input": "1\n42",
        "expectedOutput": "42"
      }
    ]
  },
  {
    "id": "cpp-ex-5-42",
    "title": "BST Search",
    "titleZh": "BST查找",
    "difficulty": "hard",
    "level": 5,
    "category": "Classic Problems",
    "categoryZh": "经典问题",
    "tags": [
      "bst",
      "search",
      "tree"
    ],
    "description": "Build a BST from n integers. Then read q queries and for each print \"Found\" or \"Not found\".\n\nInput: n, n ints, q, q queries\nOutput: Found or Not found for each",
    "descriptionZh": "在BST中查找元素。",
    "examples": [
      {
        "input": "5\n5 3 7 1 4\n2\n3\n6",
        "output": "Found\nNot found"
      }
    ],
    "starterCode": "#include <iostream>\nusing namespace std;\n\nstruct Node {\n    int val;\n    Node *left, *right;\n    Node(int v) : val(v), left(nullptr), right(nullptr) {}\n};\n\nNode* insert(Node* r, int v) {\n    if (!r) return new Node(v);\n    if (v < r->val) r->left = insert(r->left, v);\n    else r->right = insert(r->right, v);\n    return r;\n}\n\n// TODO: bool search(Node* r, int v)\n\nint main() {\n    int n; cin >> n;\n    Node* root = nullptr;\n    for (int i = 0; i < n; i++) { int v; cin >> v; root = insert(root, v); }\n    int q; cin >> q;\n    while (q--) {\n        int v; cin >> v;\n        cout << (search(root, v) ? \"Found\" : \"Not found\") << endl;\n    }\n    return 0;\n}",
    "solution": "#include <iostream>\nusing namespace std;\n\nstruct Node {\n    int val;\n    Node *left, *right;\n    Node(int v) : val(v), left(nullptr), right(nullptr) {}\n};\n\nNode* insert(Node* r, int v) {\n    if (!r) return new Node(v);\n    if (v < r->val) r->left = insert(r->left, v);\n    else r->right = insert(r->right, v);\n    return r;\n}\n\nbool search(Node* r, int v) {\n    if (!r) return false;\n    if (r->val == v) return true;\n    if (v < r->val) return search(r->left, v);\n    return search(r->right, v);\n}\n\nint main() {\n    int n; cin >> n;\n    Node* root = nullptr;\n    for (int i = 0; i < n; i++) { int v; cin >> v; root = insert(root, v); }\n    int q; cin >> q;\n    while (q--) {\n        int v; cin >> v;\n        cout << (search(root, v) ? \"Found\" : \"Not found\") << endl;\n    }\n    return 0;\n}",
    "hints": [
      "Compare and go left or right",
      "Base case: null node means not found"
    ],
    "hintsZh": [
      "比较后往左或往右",
      "基本情况：空节点表示未找到"
    ],
    "testCases": [
      {
        "input": "5\n5 3 7 1 4\n2\n3\n6",
        "expectedOutput": "Found\nNot found"
      },
      {
        "input": "3\n1 2 3\n1\n2",
        "expectedOutput": "Found"
      },
      {
        "input": "3\n1 2 3\n1\n5",
        "expectedOutput": "Not found"
      }
    ]
  },
  {
    "id": "cpp-ex-5-43",
    "title": "DFS - Graph Traversal",
    "titleZh": "DFS - 图遍历",
    "difficulty": "hard",
    "level": 5,
    "category": "Classic Problems",
    "categoryZh": "经典问题",
    "tags": [
      "dfs",
      "graph",
      "recursion"
    ],
    "description": "Read an undirected graph (n nodes, m edges, 0-indexed). Perform DFS from node 0. Print visit order.\n\nInput: n m, then m edges (u v)\nOutput: DFS visit order space-separated",
    "descriptionZh": "从节点0开始DFS遍历图。",
    "examples": [
      {
        "input": "4 4\n0 1\n0 2\n1 3\n2 3",
        "output": "0 1 3 2"
      }
    ],
    "starterCode": "#include <iostream>\n#include <vector>\nusing namespace std;\n\nvector<vector<int>> adj;\nvector<bool> visited;\n\nvoid dfs(int node) {\n    // TODO\n}\n\nint main() {\n    int n, m; cin >> n >> m;\n    adj.resize(n);\n    visited.assign(n, false);\n    for (int i = 0; i < m; i++) {\n        int u, v; cin >> u >> v;\n        adj[u].push_back(v);\n        adj[v].push_back(u);\n    }\n    dfs(0);\n    cout << endl;\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <vector>\nusing namespace std;\n\nvector<vector<int>> adj;\nvector<bool> visited;\nbool first_out = true;\n\nvoid dfs(int node) {\n    visited[node] = true;\n    if (!first_out) cout << \" \";\n    cout << node;\n    first_out = false;\n    for (int nb : adj[node]) {\n        if (!visited[nb]) dfs(nb);\n    }\n}\n\nint main() {\n    int n, m; cin >> n >> m;\n    adj.resize(n);\n    visited.assign(n, false);\n    for (int i = 0; i < m; i++) {\n        int u, v; cin >> u >> v;\n        adj[u].push_back(v);\n        adj[v].push_back(u);\n    }\n    dfs(0);\n    cout << endl;\n    return 0;\n}",
    "hints": [
      "Mark node visited, then recurse on unvisited neighbors",
      "DFS uses recursion (implicit stack)"
    ],
    "hintsZh": [
      "标记已访问，递归访问未访问的邻居",
      "DFS使用递归（隐式栈）"
    ],
    "testCases": [
      {
        "input": "4 4\n0 1\n0 2\n1 3\n2 3",
        "expectedOutput": "0 1 3 2"
      },
      {
        "input": "3 2\n0 1\n1 2",
        "expectedOutput": "0 1 2"
      },
      {
        "input": "2 1\n0 1",
        "expectedOutput": "0 1"
      }
    ]
  },
  {
    "id": "cpp-ex-5-44",
    "title": "Topological Sort",
    "titleZh": "拓扑排序",
    "difficulty": "hard",
    "level": 5,
    "category": "Classic Problems",
    "categoryZh": "经典问题",
    "tags": [
      "topological-sort",
      "dag",
      "bfs",
      "kahn"
    ],
    "description": "Read a directed acyclic graph (n nodes, m edges). Output a topological ordering using Kahn's algorithm (BFS with in-degree). Choose smallest available node first.\n\nInput: n m, then m edges (u v meaning u -> v)\nOutput: topological order space-separated",
    "descriptionZh": "用Kahn算法进行拓扑排序（优先选最小编号节点）。",
    "examples": [
      {
        "input": "4 4\n0 1\n0 2\n1 3\n2 3",
        "output": "0 1 2 3"
      }
    ],
    "starterCode": "#include <iostream>\n#include <vector>\n#include <queue>\nusing namespace std;\n\nint main() {\n    int n, m; cin >> n >> m;\n    vector<vector<int>> adj(n);\n    vector<int> indeg(n, 0);\n    // TODO: read edges, Kahn's algorithm\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <vector>\n#include <queue>\nusing namespace std;\n\nint main() {\n    int n, m; cin >> n >> m;\n    vector<vector<int>> adj(n);\n    vector<int> indeg(n, 0);\n    for (int i = 0; i < m; i++) {\n        int u, v; cin >> u >> v;\n        adj[u].push_back(v);\n        indeg[v]++;\n    }\n    priority_queue<int, vector<int>, greater<int>> pq;\n    for (int i = 0; i < n; i++) if (indeg[i] == 0) pq.push(i);\n    bool first = true;\n    while (!pq.empty()) {\n        int u = pq.top(); pq.pop();\n        if (!first) cout << \" \";\n        cout << u;\n        first = false;\n        for (int v : adj[u]) {\n            if (--indeg[v] == 0) pq.push(v);\n        }\n    }\n    cout << endl;\n    return 0;\n}",
    "hints": [
      "Start with nodes of in-degree 0",
      "Use min-heap for smallest-first ordering"
    ],
    "hintsZh": [
      "从入度为0的节点开始",
      "用最小堆保证选最小编号"
    ],
    "testCases": [
      {
        "input": "4 4\n0 1\n0 2\n1 3\n2 3",
        "expectedOutput": "0 1 2 3"
      },
      {
        "input": "3 2\n0 1\n0 2",
        "expectedOutput": "0 1 2"
      },
      {
        "input": "4 3\n1 0\n2 0\n3 0",
        "expectedOutput": "1 2 3 0"
      }
    ]
  },
  {
    "id": "cpp-ex-5-45",
    "title": "Dijkstra Shortest Path",
    "titleZh": "Dijkstra最短路径",
    "difficulty": "hard",
    "level": 5,
    "category": "Classic Problems",
    "categoryZh": "经典问题",
    "tags": [
      "dijkstra",
      "shortest-path",
      "priority-queue",
      "graph"
    ],
    "description": "Read a weighted directed graph (n nodes, m edges). Find shortest distance from node 0 to all others using Dijkstra. Print distances (-1 if unreachable).\n\nInput: n m, then m edges (u v w)\nOutput: distances from 0 to each node, space-separated",
    "descriptionZh": "用Dijkstra算法求从节点0到所有节点的最短距离。",
    "examples": [
      {
        "input": "4 5\n0 1 1\n0 2 4\n1 2 2\n1 3 6\n2 3 3",
        "output": "0 1 3 6"
      }
    ],
    "starterCode": "#include <iostream>\n#include <vector>\n#include <queue>\n#include <climits>\nusing namespace std;\n\nint main() {\n    int n, m; cin >> n >> m;\n    vector<vector<pair<int,int>>> adj(n);\n    // TODO: Dijkstra\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <vector>\n#include <queue>\n#include <climits>\nusing namespace std;\n\nint main() {\n    int n, m; cin >> n >> m;\n    vector<vector<pair<int,int>>> adj(n);\n    for (int i = 0; i < m; i++) {\n        int u, v, w; cin >> u >> v >> w;\n        adj[u].push_back({v, w});\n    }\n    vector<long long> dist(n, LLONG_MAX);\n    priority_queue<pair<long long,int>, vector<pair<long long,int>>, greater<>> pq;\n    dist[0] = 0;\n    pq.push({0, 0});\n    while (!pq.empty()) {\n        auto [d, u] = pq.top(); pq.pop();\n        if (d > dist[u]) continue;\n        for (auto [v, w] : adj[u]) {\n            if (dist[u] + w < dist[v]) {\n                dist[v] = dist[u] + w;\n                pq.push({dist[v], v});\n            }\n        }\n    }\n    for (int i = 0; i < n; i++) {\n        if (i) cout << \" \";\n        cout << (dist[i] == LLONG_MAX ? -1 : dist[i]);\n    }\n    cout << endl;\n    return 0;\n}",
    "hints": [
      "Use min-heap with (distance, node)",
      "Skip if popped distance > current best"
    ],
    "hintsZh": [
      "用最小堆存(距离, 节点)",
      "如果弹出的距离>当前最优则跳过"
    ],
    "testCases": [
      {
        "input": "4 5\n0 1 1\n0 2 4\n1 2 2\n1 3 6\n2 3 3",
        "expectedOutput": "0 1 3 6"
      },
      {
        "input": "3 3\n0 1 5\n0 2 10\n1 2 3",
        "expectedOutput": "0 5 8"
      },
      {
        "input": "3 1\n0 1 1",
        "expectedOutput": "0 1 -1"
      }
    ]
  },
  {
    "id": "cpp-ex-5-46",
    "title": "Find & Find_if",
    "titleZh": "Find与Find_if",
    "difficulty": "hard",
    "level": 5,
    "category": "STL Algorithms",
    "categoryZh": "STL算法",
    "tags": [
      "find",
      "find_if",
      "algorithm"
    ],
    "description": "Read n integers and a target. Use find to locate target. Then use find_if to find first element > target. Print positions or -1.\n\nInput: n, n integers, target\nOutput: line 1: position of target (or -1), line 2: position of first > target (or -1)",
    "descriptionZh": "用find和find_if查找元素。",
    "examples": [
      {
        "input": "5\n1 5 3 7 2\n3",
        "output": "2\n1"
      }
    ],
    "starterCode": "#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    vector<int> v(n);\n    for (int i = 0; i < n; i++) cin >> v[i];\n    int target; cin >> target;\n    // TODO\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    vector<int> v(n);\n    for (int i = 0; i < n; i++) cin >> v[i];\n    int target; cin >> target;\n    auto it1 = find(v.begin(), v.end(), target);\n    cout << (it1 != v.end() ? (int)(it1 - v.begin()) : -1) << endl;\n    auto it2 = find_if(v.begin(), v.end(), [target](int x) { return x > target; });\n    cout << (it2 != v.end() ? (int)(it2 - v.begin()) : -1) << endl;\n    return 0;\n}",
    "hints": [
      "find returns iterator to element or end()",
      "find_if takes a predicate"
    ],
    "hintsZh": [
      "find返回元素的迭代器或end()",
      "find_if接受谓词"
    ],
    "testCases": [
      {
        "input": "5\n1 5 3 7 2\n3",
        "expectedOutput": "2\n1"
      },
      {
        "input": "3\n1 2 3\n5",
        "expectedOutput": "-1\n-1"
      },
      {
        "input": "4\n10 20 30 40\n10",
        "expectedOutput": "0\n1"
      }
    ]
  },
  {
    "id": "cpp-ex-5-47",
    "title": "Lower & Upper Bound",
    "titleZh": "下界与上界",
    "difficulty": "hard",
    "level": 5,
    "category": "STL Algorithms",
    "categoryZh": "STL算法",
    "tags": [
      "lower_bound",
      "upper_bound",
      "sorted"
    ],
    "description": "Read n sorted integers and q queries. For each query x, print the index of lower_bound and upper_bound.\n\nInput: n, n sorted ints, q, q queries\nOutput: for each: lb_pos ub_pos",
    "descriptionZh": "对排序数组查询lower_bound和upper_bound的位置。",
    "examples": [
      {
        "input": "6\n1 2 2 3 3 5\n2\n2\n4",
        "output": "1 3\n5 5"
      }
    ],
    "starterCode": "#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    vector<int> v(n);\n    for (int i = 0; i < n; i++) cin >> v[i];\n    int q; cin >> q;\n    // TODO\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    vector<int> v(n);\n    for (int i = 0; i < n; i++) cin >> v[i];\n    int q; cin >> q;\n    while (q--) {\n        int x; cin >> x;\n        int lb = lower_bound(v.begin(), v.end(), x) - v.begin();\n        int ub = upper_bound(v.begin(), v.end(), x) - v.begin();\n        cout << lb << \" \" << ub << endl;\n    }\n    return 0;\n}",
    "hints": [
      "lower_bound: first >= x",
      "upper_bound: first > x"
    ],
    "hintsZh": [
      "lower_bound: 第一个>=x",
      "upper_bound: 第一个>x"
    ],
    "testCases": [
      {
        "input": "6\n1 2 2 3 3 5\n2\n2\n4",
        "expectedOutput": "1 3\n5 5"
      },
      {
        "input": "3\n1 2 3\n1\n2",
        "expectedOutput": "1 2"
      },
      {
        "input": "4\n1 1 1 1\n1\n1",
        "expectedOutput": "0 4"
      }
    ]
  },
  {
    "id": "cpp-ex-5-48",
    "title": "Priority Queue - Merge K Sorted",
    "titleZh": "优先队列 - 合并K个有序数组",
    "difficulty": "hard",
    "level": 5,
    "category": "Classic Problems",
    "categoryZh": "经典问题",
    "tags": [
      "priority_queue",
      "merge",
      "k-way"
    ],
    "description": "Read k sorted arrays. Merge them all into one sorted array using a min-heap. Print result.\n\nInput: k, then for each: n_i followed by n_i sorted ints\nOutput: merged sorted array",
    "descriptionZh": "用最小堆合并k个有序数组。",
    "examples": [
      {
        "input": "3\n3\n1 4 7\n3\n2 5 8\n3\n3 6 9",
        "output": "1 2 3 4 5 6 7 8 9"
      }
    ],
    "starterCode": "#include <iostream>\n#include <vector>\n#include <queue>\nusing namespace std;\n\nint main() {\n    int k; cin >> k;\n    // TODO: merge k sorted arrays\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <vector>\n#include <queue>\nusing namespace std;\n\nint main() {\n    int k; cin >> k;\n    vector<vector<int>> arrs(k);\n    // val, array_idx, elem_idx\n    priority_queue<tuple<int,int,int>, vector<tuple<int,int,int>>, greater<>> pq;\n    for (int i = 0; i < k; i++) {\n        int n; cin >> n;\n        arrs[i].resize(n);\n        for (int j = 0; j < n; j++) cin >> arrs[i][j];\n        if (n > 0) pq.push({arrs[i][0], i, 0});\n    }\n    bool first = true;\n    while (!pq.empty()) {\n        auto [val, ai, ei] = pq.top(); pq.pop();\n        if (!first) cout << \" \";\n        cout << val;\n        first = false;\n        if (ei + 1 < (int)arrs[ai].size()) {\n            pq.push({arrs[ai][ei + 1], ai, ei + 1});\n        }\n    }\n    cout << endl;\n    return 0;\n}",
    "hints": [
      "Push first element of each array",
      "When popping, push next element from same array"
    ],
    "hintsZh": [
      "先把每个数组的第一个元素入堆",
      "弹出时把同数组的下一个元素入堆"
    ],
    "testCases": [
      {
        "input": "3\n3\n1 4 7\n3\n2 5 8\n3\n3 6 9",
        "expectedOutput": "1 2 3 4 5 6 7 8 9"
      },
      {
        "input": "2\n2\n1 3\n2\n2 4",
        "expectedOutput": "1 2 3 4"
      },
      {
        "input": "1\n3\n5 10 15",
        "expectedOutput": "5 10 15"
      }
    ]
  },
  {
    "id": "cpp-ex-5-49",
    "title": "Graph - Connected Components",
    "titleZh": "图 - 连通分量",
    "difficulty": "hard",
    "level": 5,
    "category": "Classic Problems",
    "categoryZh": "经典问题",
    "tags": [
      "graph",
      "dfs",
      "connected-components"
    ],
    "description": "Read an undirected graph (n nodes, m edges). Count the number of connected components.\n\nInput: n m, then m edges\nOutput: number of connected components",
    "descriptionZh": "计算无向图的连通分量数。",
    "examples": [
      {
        "input": "5 3\n0 1\n1 2\n3 4",
        "output": "2"
      }
    ],
    "starterCode": "#include <iostream>\n#include <vector>\nusing namespace std;\n\nvector<vector<int>> adj;\nvector<bool> visited;\n\nvoid dfs(int u) {\n    // TODO\n}\n\nint main() {\n    int n, m; cin >> n >> m;\n    adj.resize(n);\n    visited.assign(n, false);\n    // TODO: count components\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <vector>\nusing namespace std;\n\nvector<vector<int>> adj;\nvector<bool> visited;\n\nvoid dfs(int u) {\n    visited[u] = true;\n    for (int v : adj[u]) if (!visited[v]) dfs(v);\n}\n\nint main() {\n    int n, m; cin >> n >> m;\n    adj.resize(n);\n    visited.assign(n, false);\n    for (int i = 0; i < m; i++) {\n        int u, v; cin >> u >> v;\n        adj[u].push_back(v);\n        adj[v].push_back(u);\n    }\n    int count = 0;\n    for (int i = 0; i < n; i++) {\n        if (!visited[i]) {\n            dfs(i);\n            count++;\n        }\n    }\n    cout << count << endl;\n    return 0;\n}",
    "hints": [
      "Run DFS from each unvisited node",
      "Each DFS call explores one component"
    ],
    "hintsZh": [
      "从每个未访问节点开始DFS",
      "每次DFS调用探索一个连通分量"
    ],
    "testCases": [
      {
        "input": "5 3\n0 1\n1 2\n3 4",
        "expectedOutput": "2"
      },
      {
        "input": "4 0",
        "expectedOutput": "4"
      },
      {
        "input": "3 3\n0 1\n1 2\n0 2",
        "expectedOutput": "1"
      }
    ]
  },
  {
    "id": "cpp-ex-5-50",
    "title": "Unordered Map - Group Anagrams",
    "titleZh": "哈希表 - 字母异位词分组",
    "difficulty": "hard",
    "level": 5,
    "category": "STL Containers",
    "categoryZh": "STL容器",
    "tags": [
      "unordered_map",
      "anagram",
      "string",
      "sort"
    ],
    "description": "Read n words. Group anagrams together. Print each group on a line (words sorted within group, groups sorted by first word).\n\nInput: n, then n words\nOutput: groups of anagrams, one group per line",
    "descriptionZh": "将字母异位词分组输出。",
    "examples": [
      {
        "input": "6\neat tea tan ate nat bat",
        "output": "ate eat tea\nbat\nnat tan"
      }
    ],
    "starterCode": "#include <iostream>\n#include <vector>\n#include <string>\n#include <map>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    // TODO: group anagrams\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <vector>\n#include <string>\n#include <map>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    map<string, vector<string>> groups;\n    for (int i = 0; i < n; i++) {\n        string w; cin >> w;\n        string key = w;\n        sort(key.begin(), key.end());\n        groups[key].push_back(w);\n    }\n    for (auto& [key, words] : groups) {\n        sort(words.begin(), words.end());\n        for (int i = 0; i < (int)words.size(); i++) {\n            if (i) cout << \" \";\n            cout << words[i];\n        }\n        cout << endl;\n    }\n    return 0;\n}",
    "hints": [
      "Sort each word to get anagram key",
      "Use map<string, vector<string>>"
    ],
    "hintsZh": [
      "排序每个单词作为异位词的键",
      "用map<string, vector<string>>"
    ],
    "testCases": [
      {
        "input": "6\neat tea tan ate nat bat",
        "expectedOutput": "ate eat tea\nbat\nnat tan"
      },
      {
        "input": "3\nabc bca cab",
        "expectedOutput": "abc bca cab"
      },
      {
        "input": "2\nhello world",
        "expectedOutput": "hello\nworld"
      }
    ]
  },
  {
    "id": "cpp-ex-5-51",
    "title": "Stack - Next Greater Element",
    "titleZh": "栈 - 下一个更大元素",
    "difficulty": "hard",
    "level": 5,
    "category": "Stack",
    "categoryZh": "栈",
    "tags": [
      "stack",
      "monotonic",
      "next-greater"
    ],
    "description": "Read n integers. For each element, find the next greater element to its right. Print -1 if none.\n\nInput: n, n integers\nOutput: next greater elements space-separated",
    "descriptionZh": "对每个元素找到右边第一个更大的元素。",
    "examples": [
      {
        "input": "4\n4 5 2 10",
        "output": "5 10 10 -1"
      }
    ],
    "starterCode": "#include <iostream>\n#include <vector>\n#include <stack>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    vector<int> nums(n);\n    for (int i = 0; i < n; i++) cin >> nums[i];\n    // TODO: monotonic stack\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <vector>\n#include <stack>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    vector<int> nums(n), res(n, -1);\n    for (int i = 0; i < n; i++) cin >> nums[i];\n    stack<int> st;\n    for (int i = 0; i < n; i++) {\n        while (!st.empty() && nums[st.top()] < nums[i]) {\n            res[st.top()] = nums[i];\n            st.pop();\n        }\n        st.push(i);\n    }\n    for (int i = 0; i < n; i++) {\n        if (i) cout << \" \";\n        cout << res[i];\n    }\n    cout << endl;\n    return 0;\n}",
    "hints": [
      "Use monotonic decreasing stack of indices",
      "Pop when current > stack top"
    ],
    "hintsZh": [
      "使用单调递减栈存储索引",
      "当前元素>栈顶时弹出"
    ],
    "testCases": [
      {
        "input": "4\n4 5 2 10",
        "expectedOutput": "5 10 10 -1"
      },
      {
        "input": "3\n3 2 1",
        "expectedOutput": "-1 -1 -1"
      },
      {
        "input": "3\n1 2 3",
        "expectedOutput": "2 3 -1"
      }
    ]
  },
  {
    "id": "cpp-ex-5-52",
    "title": "Priority Queue - Task Scheduler",
    "titleZh": "优先队列 - 任务调度",
    "difficulty": "hard",
    "level": 5,
    "category": "STL Containers",
    "categoryZh": "STL容器",
    "tags": [
      "priority_queue",
      "greedy",
      "scheduling"
    ],
    "description": "Read n tasks with durations. Schedule tasks by shortest duration first (greedy). Print the order and total completion time (sum of all completion times).\n\nInput: n, n durations\nOutput: line 1: order of durations, line 2: total completion time",
    "descriptionZh": "按最短作业优先调度，输出顺序和总完成时间。",
    "examples": [
      {
        "input": "3\n3 1 2",
        "output": "1 2 3\n10"
      }
    ],
    "starterCode": "#include <iostream>\n#include <vector>\n#include <queue>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    priority_queue<int, vector<int>, greater<int>> pq;\n    // TODO\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <vector>\n#include <queue>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    priority_queue<int, vector<int>, greater<int>> pq;\n    for (int i = 0; i < n; i++) {\n        int d; cin >> d;\n        pq.push(d);\n    }\n    long long total = 0, running = 0;\n    bool first = true;\n    while (!pq.empty()) {\n        int d = pq.top(); pq.pop();\n        if (!first) cout << \" \";\n        cout << d;\n        first = false;\n        running += d;\n        total += running;\n    }\n    cout << \"\\n\" << total << endl;\n    return 0;\n}",
    "hints": [
      "Min-heap gives shortest first",
      "Total = sum of all completion times"
    ],
    "hintsZh": [
      "最小堆给出最短的",
      "总时间 = 所有完成时间之和"
    ],
    "testCases": [
      {
        "input": "3\n3 1 2",
        "expectedOutput": "1 2 3\n10"
      },
      {
        "input": "4\n4 3 2 1",
        "expectedOutput": "1 2 3 4\n20"
      },
      {
        "input": "2\n5 5",
        "expectedOutput": "5 5\n15"
      }
    ]
  },
  {
    "id": "cpp-ex-5-53",
    "title": "Vector - Rotate",
    "titleZh": "向量 - 旋转",
    "difficulty": "hard",
    "level": 5,
    "category": "STL Algorithms",
    "categoryZh": "STL算法",
    "tags": [
      "rotate",
      "vector",
      "algorithm"
    ],
    "description": "Read n integers and k. Rotate the array left by k positions using std::rotate. Print result.\n\nInput: n k, then n integers\nOutput: rotated array space-separated",
    "descriptionZh": "用std::rotate将数组左旋k位。",
    "examples": [
      {
        "input": "5 2\n1 2 3 4 5",
        "output": "3 4 5 1 2"
      }
    ],
    "starterCode": "#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    int n, k; cin >> n >> k;\n    vector<int> v(n);\n    for (int i = 0; i < n; i++) cin >> v[i];\n    // TODO: rotate left by k\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    int n, k; cin >> n >> k;\n    vector<int> v(n);\n    for (int i = 0; i < n; i++) cin >> v[i];\n    k %= n;\n    rotate(v.begin(), v.begin() + k, v.end());\n    for (int i = 0; i < n; i++) {\n        if (i) cout << \" \";\n        cout << v[i];\n    }\n    cout << endl;\n    return 0;\n}",
    "hints": [
      "rotate(first, new_first, last)",
      "Handle k >= n with modulo"
    ],
    "hintsZh": [
      "rotate(first, 新起点, last)",
      "用取模处理k>=n"
    ],
    "testCases": [
      {
        "input": "5 2\n1 2 3 4 5",
        "expectedOutput": "3 4 5 1 2"
      },
      {
        "input": "4 1\n1 2 3 4",
        "expectedOutput": "2 3 4 1"
      },
      {
        "input": "3 3\n1 2 3",
        "expectedOutput": "1 2 3"
      }
    ]
  },
  {
    "id": "cpp-ex-5-54",
    "title": "Map - LRU Key Check",
    "titleZh": "Map - LRU键检查",
    "difficulty": "hard",
    "level": 5,
    "category": "STL Containers",
    "categoryZh": "STL容器",
    "tags": [
      "map",
      "find",
      "erase",
      "design"
    ],
    "description": "Simulate a simple key-value store. Read operations: \"put k v\", \"get k\", \"del k\". For get, print value or \"null\".\n\nInput: n, then n operations\nOutput: result of each get",
    "descriptionZh": "模拟简单键值存储，支持put/get/del。",
    "examples": [
      {
        "input": "5\nput a 1\nput b 2\nget a\ndel a\nget a",
        "output": "1\nnull"
      }
    ],
    "starterCode": "#include <iostream>\n#include <map>\n#include <string>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    map<string, string> store;\n    // TODO\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <map>\n#include <string>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    map<string, string> store;\n    while (n--) {\n        string op; cin >> op;\n        if (op == \"put\") {\n            string k, v; cin >> k >> v;\n            store[k] = v;\n        } else if (op == \"get\") {\n            string k; cin >> k;\n            auto it = store.find(k);\n            cout << (it != store.end() ? it->second : \"null\") << endl;\n        } else {\n            string k; cin >> k;\n            store.erase(k);\n        }\n    }\n    return 0;\n}",
    "hints": [
      "Use find to check existence",
      "erase by key removes the entry"
    ],
    "hintsZh": [
      "用find检查是否存在",
      "按键erase删除条目"
    ],
    "testCases": [
      {
        "input": "5\nput a 1\nput b 2\nget a\ndel a\nget a",
        "expectedOutput": "1\nnull"
      },
      {
        "input": "3\nget x\nput x 5\nget x",
        "expectedOutput": "null\n5"
      },
      {
        "input": "4\nput k v\nput k w\nget k\ndel k",
        "expectedOutput": "w"
      }
    ]
  },
  {
    "id": "cpp-ex-5-55",
    "title": "Unique Ptr - Polymorphism",
    "titleZh": "独占指针 - 多态",
    "difficulty": "hard",
    "level": 5,
    "category": "Smart Pointers",
    "categoryZh": "智能指针",
    "tags": [
      "unique_ptr",
      "polymorphism",
      "virtual"
    ],
    "description": "Create Shape hierarchy with Circle and Rectangle. Use unique_ptr<Shape> to store objects. Read shapes and print areas.\n\nInput: n, then n lines: \"C radius\" or \"R width height\"\nOutput: area of each with 2 decimal places",
    "descriptionZh": "用unique_ptr实现多态Shape层次。",
    "examples": [
      {
        "input": "2\nC 5\nR 3 4",
        "output": "78.54\n12.00"
      }
    ],
    "starterCode": "#include <iostream>\n#include <memory>\n#include <vector>\n#include <iomanip>\nusing namespace std;\n\nclass Shape {\npublic:\n    virtual double area() = 0;\n    virtual ~Shape() = default;\n};\n\n// TODO: Circle, Rectangle, main\n\nint main() {\n    int n; cin >> n;\n    // TODO\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <memory>\n#include <vector>\n#include <iomanip>\nusing namespace std;\n\nclass Shape {\npublic:\n    virtual double area() = 0;\n    virtual ~Shape() = default;\n};\n\nclass Circle : public Shape {\n    double r;\npublic:\n    Circle(double r) : r(r) {}\n    double area() override { return 3.14159265358979 * r * r; }\n};\n\nclass Rectangle : public Shape {\n    double w, h;\npublic:\n    Rectangle(double w, double h) : w(w), h(h) {}\n    double area() override { return w * h; }\n};\n\nint main() {\n    int n; cin >> n;\n    vector<unique_ptr<Shape>> shapes;\n    for (int i = 0; i < n; i++) {\n        char type; cin >> type;\n        if (type == 'C') {\n            double r; cin >> r;\n            shapes.push_back(make_unique<Circle>(r));\n        } else {\n            double w, h; cin >> w >> h;\n            shapes.push_back(make_unique<Rectangle>(w, h));\n        }\n    }\n    cout << fixed << setprecision(2);\n    for (auto& s : shapes) cout << s->area() << endl;\n    return 0;\n}",
    "hints": [
      "make_unique<Derived>(args) returns unique_ptr<Derived>",
      "Store as unique_ptr<Base> for polymorphism"
    ],
    "hintsZh": [
      "make_unique<派生类>(参数)返回unique_ptr",
      "存为unique_ptr<基类>实现多态"
    ],
    "testCases": [
      {
        "input": "2\nC 5\nR 3 4",
        "expectedOutput": "78.54\n12.00"
      },
      {
        "input": "1\nC 1",
        "expectedOutput": "3.14"
      },
      {
        "input": "1\nR 10 10",
        "expectedOutput": "100.00"
      }
    ]
  },
  {
    "id": "cpp-ex-5-56",
    "title": "Set - Intersection & Union",
    "titleZh": "集合 - 交集与并集",
    "difficulty": "hard",
    "level": 5,
    "category": "STL Algorithms",
    "categoryZh": "STL算法",
    "tags": [
      "set",
      "set_intersection",
      "set_union"
    ],
    "description": "Read two sets of integers. Print their intersection and union (both sorted).\n\nInput: n, n ints, m, m ints\nOutput: line 1: intersection, line 2: union",
    "descriptionZh": "输出两个集合的交集和并集。",
    "examples": [
      {
        "input": "4\n1 2 3 4\n3\n3 4 5",
        "output": "3 4\n1 2 3 4 5"
      }
    ],
    "starterCode": "#include <iostream>\n#include <vector>\n#include <set>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    set<int> a;\n    for (int i = 0; i < n; i++) { int x; cin >> x; a.insert(x); }\n    int m; cin >> m;\n    set<int> b;\n    for (int i = 0; i < m; i++) { int x; cin >> x; b.insert(x); }\n    // TODO: intersection and union\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <vector>\n#include <set>\n#include <algorithm>\n#include <iterator>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    set<int> a;\n    for (int i = 0; i < n; i++) { int x; cin >> x; a.insert(x); }\n    int m; cin >> m;\n    set<int> b;\n    for (int i = 0; i < m; i++) { int x; cin >> x; b.insert(x); }\n    vector<int> inter, uni;\n    set_intersection(a.begin(), a.end(), b.begin(), b.end(), back_inserter(inter));\n    set_union(a.begin(), a.end(), b.begin(), b.end(), back_inserter(uni));\n    for (int i = 0; i < (int)inter.size(); i++) {\n        if (i) cout << \" \";\n        cout << inter[i];\n    }\n    cout << endl;\n    for (int i = 0; i < (int)uni.size(); i++) {\n        if (i) cout << \" \";\n        cout << uni[i];\n    }\n    cout << endl;\n    return 0;\n}",
    "hints": [
      "Both inputs must be sorted (set is sorted)",
      "Use back_inserter for output"
    ],
    "hintsZh": [
      "两个输入必须有序（set已排序）",
      "用back_inserter作为输出迭代器"
    ],
    "testCases": [
      {
        "input": "4\n1 2 3 4\n3\n3 4 5",
        "expectedOutput": "3 4\n1 2 3 4 5"
      },
      {
        "input": "2\n1 2\n2\n3 4",
        "expectedOutput": "\n1 2 3 4"
      },
      {
        "input": "3\n1 2 3\n3\n1 2 3",
        "expectedOutput": "1 2 3\n1 2 3"
      }
    ]
  },
  {
    "id": "cpp-ex-5-57",
    "title": "Deque as Double-Ended Queue",
    "titleZh": "双端队列操作",
    "difficulty": "hard",
    "level": 5,
    "category": "STL Containers",
    "categoryZh": "STL容器",
    "tags": [
      "deque",
      "push_front",
      "push_back"
    ],
    "description": "Read operations: \"pf x\" (push_front), \"pb x\" (push_back), \"popf\" (pop_front), \"popb\" (pop_back), \"print\". Execute and print when asked.\n\nInput: n, then n operations\nOutput: result of each print operation",
    "descriptionZh": "用deque执行双端操作。",
    "examples": [
      {
        "input": "5\npb 1\npb 2\npf 3\npf 4\nprint",
        "output": "4 3 1 2"
      }
    ],
    "starterCode": "#include <iostream>\n#include <deque>\n#include <string>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    deque<int> dq;\n    // TODO\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <deque>\n#include <string>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    deque<int> dq;\n    while (n--) {\n        string op; cin >> op;\n        if (op == \"pf\") { int x; cin >> x; dq.push_front(x); }\n        else if (op == \"pb\") { int x; cin >> x; dq.push_back(x); }\n        else if (op == \"popf\") { dq.pop_front(); }\n        else if (op == \"popb\") { dq.pop_back(); }\n        else {\n            for (int i = 0; i < (int)dq.size(); i++) {\n                if (i) cout << \" \";\n                cout << dq[i];\n            }\n            cout << endl;\n        }\n    }\n    return 0;\n}",
    "hints": [
      "deque supports push/pop at both ends",
      "O(1) for all four operations"
    ],
    "hintsZh": [
      "deque支持两端的push/pop",
      "四种操作都是O(1)"
    ],
    "testCases": [
      {
        "input": "5\npb 1\npb 2\npf 3\npf 4\nprint",
        "expectedOutput": "4 3 1 2"
      },
      {
        "input": "4\npb 1\npb 2\npopf\nprint",
        "expectedOutput": "2"
      },
      {
        "input": "4\npf 1\npf 2\npopb\nprint",
        "expectedOutput": "2"
      }
    ]
  },
  {
    "id": "cpp-ex-5-58",
    "title": "STL Partition",
    "titleZh": "STL分区",
    "difficulty": "hard",
    "level": 5,
    "category": "STL Algorithms",
    "categoryZh": "STL算法",
    "tags": [
      "partition",
      "stable_partition",
      "algorithm"
    ],
    "description": "Read n integers and a pivot. Use stable_partition to move elements <= pivot before elements > pivot. Print result.\n\nInput: n, n integers, pivot\nOutput: partitioned array",
    "descriptionZh": "用stable_partition按pivot分区。",
    "examples": [
      {
        "input": "6\n5 1 3 2 4 6\n3",
        "output": "1 3 2 5 4 6"
      }
    ],
    "starterCode": "#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    vector<int> v(n);\n    for (int i = 0; i < n; i++) cin >> v[i];\n    int pivot; cin >> pivot;\n    // TODO: stable_partition\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    vector<int> v(n);\n    for (int i = 0; i < n; i++) cin >> v[i];\n    int pivot; cin >> pivot;\n    stable_partition(v.begin(), v.end(), [pivot](int x) { return x <= pivot; });\n    for (int i = 0; i < n; i++) {\n        if (i) cout << \" \";\n        cout << v[i];\n    }\n    cout << endl;\n    return 0;\n}",
    "hints": [
      "stable_partition preserves relative order",
      "Predicate returns true for left partition"
    ],
    "hintsZh": [
      "stable_partition保持相对顺序",
      "谓词为左分区返回true"
    ],
    "testCases": [
      {
        "input": "6\n5 1 3 2 4 6\n3",
        "expectedOutput": "1 3 2 5 4 6"
      },
      {
        "input": "4\n4 3 2 1\n2",
        "expectedOutput": "2 1 4 3"
      },
      {
        "input": "3\n1 2 3\n5",
        "expectedOutput": "1 2 3"
      }
    ]
  },
  {
    "id": "cpp-ex-5-59",
    "title": "Map - Frequency Sort",
    "titleZh": "Map - 频率排序",
    "difficulty": "hard",
    "level": 5,
    "category": "STL Containers",
    "categoryZh": "STL容器",
    "tags": [
      "map",
      "sort",
      "frequency"
    ],
    "description": "Read n integers. Sort by frequency descending; if equal frequency, by value ascending. Print result.\n\nInput: n, n integers\nOutput: sorted by frequency",
    "descriptionZh": "按频率降序排序，频率相同按值升序。",
    "examples": [
      {
        "input": "7\n1 1 2 2 2 3 3",
        "output": "2 2 2 1 1 3 3"
      }
    ],
    "starterCode": "#include <iostream>\n#include <vector>\n#include <map>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    vector<int> v(n);\n    for (int i = 0; i < n; i++) cin >> v[i];\n    // TODO: frequency sort\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <vector>\n#include <map>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    vector<int> v(n);\n    map<int,int> freq;\n    for (int i = 0; i < n; i++) { cin >> v[i]; freq[v[i]]++; }\n    sort(v.begin(), v.end(), [&freq](int a, int b) {\n        if (freq[a] != freq[b]) return freq[a] > freq[b];\n        return a < b;\n    });\n    for (int i = 0; i < n; i++) {\n        if (i) cout << \" \";\n        cout << v[i];\n    }\n    cout << endl;\n    return 0;\n}",
    "hints": [
      "Count frequencies first",
      "Lambda captures freq by reference"
    ],
    "hintsZh": [
      "先统计频率",
      "lambda按引用捕获freq"
    ],
    "testCases": [
      {
        "input": "7\n1 1 2 2 2 3 3",
        "expectedOutput": "2 2 2 1 1 3 3"
      },
      {
        "input": "4\n4 3 2 1",
        "expectedOutput": "1 2 3 4"
      },
      {
        "input": "5\n5 5 5 5 5",
        "expectedOutput": "5 5 5 5 5"
      }
    ]
  },
  {
    "id": "cpp-ex-5-60",
    "title": "Shared Ptr - Observer Pattern",
    "titleZh": "共享指针 - 观察者模式",
    "difficulty": "hard",
    "level": 5,
    "category": "Smart Pointers",
    "categoryZh": "智能指针",
    "tags": [
      "shared_ptr",
      "weak_ptr",
      "design-pattern"
    ],
    "description": "Create a Subject that holds a value. Observers (via shared_ptr) can read it. Read operations: \"set x\" to set value, \"get\" to print value, \"count\" to print observer count.\n\nInput: n operations\nOutput: results of get and count",
    "descriptionZh": "用shared_ptr实现简单观察者，支持set/get/count。",
    "examples": [
      {
        "input": "4\nset 42\nget\ncount\nget",
        "output": "42\n1\n42"
      }
    ],
    "starterCode": "#include <iostream>\n#include <memory>\n#include <string>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    auto data = make_shared<int>(0);\n    // TODO\n    return 0;\n}",
    "solution": "#include <iostream>\n#include <memory>\n#include <string>\nusing namespace std;\n\nint main() {\n    int n; cin >> n;\n    auto data = make_shared<int>(0);\n    while (n--) {\n        string op; cin >> op;\n        if (op == \"set\") {\n            int x; cin >> x;\n            *data = x;\n        } else if (op == \"get\") {\n            cout << *data << endl;\n        } else {\n            cout << data.use_count() << endl;\n        }\n    }\n    return 0;\n}",
    "hints": [
      "Dereference shared_ptr with *",
      "use_count() gives number of owners"
    ],
    "hintsZh": [
      "用*解引用shared_ptr",
      "use_count()给出所有者数量"
    ],
    "testCases": [
      {
        "input": "4\nset 42\nget\ncount\nget",
        "expectedOutput": "42\n1\n42"
      },
      {
        "input": "3\nset 10\nset 20\nget",
        "expectedOutput": "20"
      },
      {
        "input": "2\nget\ncount",
        "expectedOutput": "0\n1"
      }
    ]
  }
];
